Repository VKCOM/kphp, pull requests merged in 2021-05, with the labels that each got.

#230 Replace long dash with short one for the compiler result table.
  compiler/code-gen/code-gen-task.cpp
Labels: small fix

#233 Support pch for clang build.
  compiler/code-gen/files/function-header.cpp
  compiler/code-gen/files/function-source.cpp
  compiler/code-gen/files/global_vars_memory_stats.cpp
  compiler/code-gen/files/init-scripts.cpp
  compiler/code-gen/files/lib-header.cpp
  compiler/code-gen/files/tl2cpp/tl-module.cpp
  compiler/code-gen/files/tl2cpp/tl2cpp.cpp
  compiler/code-gen/files/type-tagger.cpp
  compiler/code-gen/files/vars-cpp.cpp
  compiler/code-gen/files/vars-reset.cpp
  compiler/compiler-settings.cpp
  compiler/compiler-settings.h
  compiler/kphp2cpp.cpp
  compiler/make/cpp-to-obj-target.h
  compiler/make/make.cpp
Labels: small fix

#237 don't create net_event on empty RPC results receiving
  server/php-engine.cpp
Labels: small fix

#240 Job workers: enhancements
  common/pipe-utils.cpp
  common/pipe-utils.h
  functions.txt
  runtime/interface.cpp
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/job-interface.cpp
  runtime/job-workers/job-interface.h
  server/job-workers/job-message.h
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-master.cpp
  server/php-runner.cpp
  server/php-worker-stats.cpp
  server/php-worker-stats.h
  server/php-worker.cpp
  tests/cpp/server/job-workers/shared-memory-manager-test.cpp
  tests/python/tests/job_workers/php/SyncJobCommand.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_job_worker_wakeup.py
Labels: enhancement

#243 Fix interfaces codegen: gen pure functions.
  compiler/code-gen/declarations.cpp
  tests/phpt/job_workers/1_interface_compilation.php
  tests/python/tests/job_workers/php/ComplexScenario/CollectStatsJobRequest.php
  tests/python/tests/job_workers/php/ComplexScenario/NetPid.php
  tests/python/tests/job_workers/php/ComplexScenario/StatTraits.php
  tests/python/tests/job_workers/php/ComplexScenario/StatsInterface.php
  tests/python/tests/job_workers/php/ComplexScenario/StatsMC.php
  tests/python/tests/job_workers/php/ComplexScenario/StatsRPCBase.php
  tests/python/tests/job_workers/php/ComplexScenario/StatsRPCFiltered.php
  tests/python/tests/job_workers/php/ComplexScenario/StatsRPCSimple.php
  tests/python/tests/job_workers/php/ComplexScenario/StatsWithFilter.php
  tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
  tests/python/tests/job_workers/php/ComplexScenario/_job_scenario.php
  tests/python/tests/job_workers/php/ComplexScenario/_stats_processor.php
Labels: bug, enhancement

#241 Fix negative keys bug
  runtime/array.inl
  runtime/array_decl.inl
  runtime/instance-copy-processor.cpp
  runtime/instance-copy-processor.h
  tests/phpt/array/015_array_replace_neg_keys.php
Labels: bug, optimization, refactoring

#235 Use default malloc instead of script memory for curl.
  common/macos-ports.h
  runtime/curl.cpp
  runtime/curl.h
  runtime/global_storage.h
  runtime/interface.cpp
  runtime/openssl.cpp
  runtime/openssl.h
  runtime/string-list.h
  runtime/timelib_wrapper.cpp
  runtime/timelib_wrapper.h
  server/php-runner.cpp
  server/php-worker-stats.cpp
  server/php-worker-stats.h
  tests/cpp/runtime/runtime-tests.cmake
  tests/cpp/runtime/string-list-test.cpp
  tests/python/lib/kphp_server.py
  tests/python/tests/curl/__init__.py
  tests/python/tests/curl/php/index.php
  tests/python/tests/curl/test_curl.py
Labels: bug, help wanted, refactoring

#236 added initial support for the `__toString()` magic method
  common/php-functions.h
  compiler/compiler.cpp
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  compiler/gentree.cpp
  compiler/pipes/check-conversions.cpp
  compiler/pipes/filter-only-actually-used.cpp
  compiler/pipes/final-check.cpp
  compiler/pipes/final-check.h
  compiler/pipes/optimization.cpp
  compiler/pipes/optimization.h
  tests/phpt/cl/181_toString_magic_method_echo.php
  tests/phpt/cl/182_toString_magic_method_call_function.php
  tests/phpt/cl/183_toString_magic_method_wrong_signature.php
  tests/phpt/cl/184_toString_magic_method_iface.php
  tests/phpt/cl/185_toString_magic_method_inherit.php
  tests/phpt/cl/186_toString_magic_method_inherit_abstract.php
  tests/phpt/cl/187_toString_magic_method_trait.php
  tests/phpt/cl/188_toString_magic_method_inherit_large_nesting.php
  tests/phpt/cl/189_toString_magic_method_inherit_without_tostring_in_parent.php
  tests/phpt/cl/190_toString_magic_method_nullable_return_type.php
  tests/phpt/cl/191_toString_magic_method_string_builder.php
Labels: enhancement

#244 Forbid reumable calls in foreach by reference from non local vars
  compiler/data/function-data.h
  compiler/pipes/calc-bad-vars.cpp
  compiler/pipes/check-nested-foreach.cpp
  compiler/pipes/check-nested-foreach.h
  tests/phpt/fork/025_foreach_by_global_var_ref_error.php
  tests/phpt/fork/026_foreach_by_class_static_var_ref_error.php
  tests/phpt/fork/027_foreach_by_static_var_ref_error.php
  tests/phpt/fork/028_foreach_by_instance_field_ref_error.php
Labels: bug

#219 enable instanceof smart casts for unions
  compiler/class-assumptions.cpp
  tests/phpt/smart_casts/05_unions.php
  tests/phpt/smart_casts/06_unions_with_interfaces.php
  tests/phpt/smart_casts/07_nullable_class.php
Labels: small fix
