Repository VKCOM/kphp, pull requests merged in 2021-08, with the labels that each got.

#287 allow empty escape_char in fgetcsv/fputcsv functions
  runtime/streams.cpp
  tests/phpt/streams/csv_input.txt
  tests/phpt/streams/fgetcsv.php
  tests/phpt/streams/fputcsv.php
Labels: PHP7.4

#289 Use relative path in #include directives for headers from static libs
  compiler/code-gen/includes.cpp
  compiler/code-gen/includes.h
  compiler/data/lib-data.h
Labels: enhancement

#285 change the default PHP version in tests to PHP7.4 instead of PHP7.2
  compiler/pipes/convert-list-assignments.cpp
  tests/kphp_tester.py
  tests/phpt/cl/005_cast_instance_to_array.php
  tests/phpt/cl/008_fields_default_value.php
  tests/phpt/cl/025_class_depends_kphp_inline.php
  tests/phpt/curl/4_curl_get_info.php
  tests/phpt/dl/1022_change_order_for_assignment_to_list.php
  tests/phpt/dl/1023_short_list_assignment.php
  tests/phpt/dl/483_bcmath.php
  tests/phpt/dl/496_regex.php
  tests/phpt/eval_order/001_list_array_index.php
  tests/phpt/interfaces/signature_compatibility/abstract_param_variadic.php
  tests/phpt/interfaces/signature_compatibility/abstract_return_derived.php
  tests/phpt/interfaces/signature_compatibility/abstract_static_param.php
  tests/phpt/interfaces/signature_compatibility/abstract_static_return_derived.php
  tests/phpt/interfaces/signature_compatibility/iface_return_derived.php
  tests/phpt/interfaces/signature_compatibility/iface_return_nullable3.php
  tests/phpt/interfaces/signature_compatibility/iface_return_nullable4.php
  tests/phpt/msgpack_serialize/000_primitives_hints.php
  tests/phpt/msgpack_serialize/005_with_namespaces_hints.php
  tests/phpt/null_coalescing/12_assignment.php
  tests/phpt/null_coalescing/13_assignment_call_rhs.php
  tests/phpt/null_coalescing/14_assignment_throw_exceptions.php
  tests/phpt/numeric_literal_separator/001_numeric_literal_ok.php
  tests/phpt/phc/parsing/php7_4/arglist_trailing_comma.php
  tests/phpt/phc/parsing/php7_4/arglist_trailing_comma_bad1.php
  tests/phpt/phc/parsing/php7_4/arglist_trailing_comma_bad2.php
  tests/phpt/phc/parsing/php7_4/arglist_trailing_comma_bad3.php
  tests/phpt/phc/parsing/php7_4/arglist_trailing_comma_bad4.php
  tests/phpt/phc/parsing/php7_4/arrowfunc.php
  tests/phpt/phc/parsing/php7_4/arrowfunc_list.php
  tests/phpt/phc/parsing/php7_4/arrowfunc_semireserved.php
  tests/phpt/phc/parsing/php7_4/arrowfunc_static.php
  tests/phpt/phc/parsing/php7_4/arrowfunc_this.php
  tests/phpt/regexp/006_preg_quote.php
  tests/phpt/regexp/007_preg_offset_capture_padding.php
  tests/phpt/spread/001_spread.php
  tests/phpt/stacktrace/07_stacktrace.php
  tests/phpt/stacktrace/09_stacktrace.php
  tests/phpt/streams/fgetcsv.php
  tests/phpt/streams/fputcsv.php
  tests/phpt/string_functions/001_strip_tags_7_4.php
  tests/phpt/string_functions/003_strip_tags_mixed_arg.php
  tests/phpt/timelib/strtotime.php
  tests/phpt/typehints/fields/01_field_type_hint.php
  tests/phpt/typehints/fields/02_field_type_hint_self.php
  tests/phpt/typehints/fields/03_field_type_hint_array.php
  tests/python/lib/file_utils.py
  tests/zend-test-list
Labels: PHP7.4

#291 Add basic benchmarks.
  tests/benchmarks/BenchmarkBasic.php
  tests/benchmarks/BenchmarkMicro.php
  tests/benchmarks/README.md
Labels: documentation

#265 Enable smartcasts for opset inside condition
  compiler/gentree.cpp
  compiler/pipes/cfg.cpp
  tests/phpt/dl/1030_ternary_fails.php
  tests/phpt/dl/1031_shorthand_ternary_fails.php
  tests/phpt/optional/004_operations.php
  tests/phpt/smart_casts/08_auto_drop_optional_inside_condition.php
Labels: optimization

#293 Job workers improvements
  compiler/code-gen/declarations.cpp
  runtime/class_instance_decl.inl
  runtime/instance-cache.cpp
  runtime/instance-copy-processor.cpp
  runtime/instance-copy-processor.h
  runtime/job-workers/job-interface.h
  runtime/job-workers/processing-jobs.cpp
  runtime/kphp_type_traits.h
  runtime/refcountable_php_classes.h
  runtime/shape.h
  tests/cpp/runtime/kphp-type-traits-test.cpp
  tests/cpp/runtime/runtime-tests.cmake
  tests/phpt/instance_cache/1_instance_cache.php
  tests/phpt/job_workers/1_interface_compilation.php
  tests/phpt/memory_usage/2_classes.php
  tests/phpt/memory_usage/3_lambdas.php
  tests/phpt/memory_usage/4_interfaces.php
  tests/phpt/memory_usage/5_polymorphic_classes.php
  tests/python/tests/instance_cache/__init__.py
  tests/python/tests/instance_cache/php/index.php
  tests/python/tests/instance_cache/test_store_fetch_delete.py
  tests/python/tests/job_workers/php/ReferenceInvariant/ReferenceInvariantData.php
  tests/python/tests/job_workers/php/ReferenceInvariant/ReferenceInvariantRequest.php
  tests/python/tests/job_workers/php/ReferenceInvariant/ReferenceInvariantResponse.php
  tests/python/tests/job_workers/php/ReferenceInvariant/TestAbstractClassA.php
  tests/python/tests/job_workers/php/ReferenceInvariant/TestClassA.php
  tests/python/tests/job_workers/php/ReferenceInvariant/TestClassAB.php
  tests/python/tests/job_workers/php/ReferenceInvariant/TestClassB.php
  tests/python/tests/job_workers/php/ReferenceInvariant/TestInterfaceA.php
  tests/python/tests/job_workers/php/ReferenceInvariant/TestInterfaceB.php
  tests/python/tests/job_workers/php/ReferenceInvariant/http_worker.php
  tests/python/tests/job_workers/php/ReferenceInvariant/job_worker.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_messages_references.py
Labels: bug, enhancement, help wanted

#288 mysql with user, password, port and remote host, utf8 header parameter
  net/net-mysql-client.cpp
  net/net-mysql-client.h
  runtime/interface.cpp
  runtime/interface.h
  server/php-engine.cpp
  server/php-sql-connections.cpp
  server/php-sql-connections.h
Labels: enhancement
