Repository VKCOM/kphp, pull requests merged in 2021-03, with the labels that each got.

#146 implemented negative offsets for regexps + offset overflow errors
  runtime/regexp.cpp
  tests/phpt/regexp/003_preg_match_neg_offset.php
  tests/phpt/regexp/004_preg_match_high_offset.php
Labels: PHP7.4, enhancement

#151 Fix docs
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
Labels: documentation

#147 Check if array is pseudo vector for msgpack serialization.
  runtime/array.inl
  runtime/array_decl.inl
  runtime/json-functions.h
  runtime/msgpack-serialization.h
  tests/phpt/msgpack_serialize/024_serialize_vector.php
Labels: bug

#141 Fix warning in array_rand when num less then array size
  runtime/array_functions.h
  tests/phpt/array/014_array_rand.php
Labels: bug

#140 potential fix of broken new ios emoji encoding
  runtime/vkext.cpp
  vkext/vkext.cpp
Labels: bug

#153 Support sha224, sha384, sha512 for hash() and hash_hmac().
  functions.txt
  runtime/openssl.cpp
  runtime/openssl.h
  tests/phpt/openssl/5_hash.php
Labels: enhancement, refactoring

#139 support php 7.4 class type hints
  compiler/data/class-members.cpp
  compiler/data/class-members.h
  compiler/data/lambda-generator.cpp
  compiler/gentree.cpp
  compiler/gentree.h
  compiler/pipes/parse-and-apply-phpdoc.cpp
  compiler/pipes/sort-and-inherit-classes.cpp
  tests/phpt/cl/005_cast_instance_to_array.php
  tests/phpt/cl/008_fields_default_value.php
  tests/phpt/cl/025_class_depends_kphp_inline.php
  tests/phpt/msgpack_serialize/000_primitives.php
  tests/phpt/msgpack_serialize/000_primitives_hints.php
  tests/phpt/msgpack_serialize/005_with_namespaces_hints.php
  tests/phpt/reqtyping/030_req_class_typing_1.php
  tests/phpt/stacktrace/07_stacktrace.php
  tests/phpt/stacktrace/09_stacktrace.php
  tests/phpt/typehints/fields/01_field_type_hint.php
  tests/phpt/typehints/fields/02_field_type_hint_self.php
  tests/phpt/typehints/fields/03_field_type_hint_array.php
Labels: PHP7.4, enhancement

#152 maintain kphp.startLeaseV2 with actor_id
  common/tl/constants/kphp.h
  server/php-engine.cpp
  server/php-lease.cpp
  server/php-lease.h
Labels: enhancement

#143 make `strict_types=1` disable automatic cast insertion for a current file
  compiler/data/src-file.h
  compiler/gentree.cpp
  compiler/phpdoc.cpp
  compiler/phpdoc.h
  compiler/pipes/collect-main-edges.cpp
  compiler/pipes/preprocess-function.cpp
  docs/kphp-language/static-type-system/type-casting.md
  tests/phpt/declare/01_strict_types.php
  tests/phpt/declare/01_strict_types.php.inc
  tests/phpt/declare/02_strict_types2.php
  tests/phpt/declare/02_strict_types2.php.inc
  tests/phpt/declare/03_strict_types_error.php
  tests/phpt/declare/03_strict_types_error.php.inc
  tests/phpt/declare/04_strict_types_kphpinfercast.php
  tests/phpt/declare/04_strict_types_kphpinfercast.php.inc
  tests/phpt/declare/05_strict_types_kphpinfercast2.php
  tests/phpt/declare/05_strict_types_kphpinfercast2.php.inc
  tests/phpt/declare/06_strict_types_kphpinfercast_error.php
  tests/phpt/declare/06_strict_types_kphpinfercast_error.php.inc
  tests/phpt/declare/07_strict_types_kphpinfercast_error.php
  tests/phpt/declare/08_strict_types_kphpinfercast.php
  tests/phpt/declare/09_strict_types_not_enabled.php
  tests/phpt/declare/09_strict_types_not_enabled.php.inc
  tests/phpt/declare/can_call_with_cast.php.inc
  tests/phpt/declare/cant_call_with_cast.php.inc
  tests/phpt/declare/infercast_func.php.inc
Labels: enhancement

#144 make strip_tags accept array as $allow, remove implicit cast from substr_replace
  functions.txt
  runtime/string_functions.cpp
  runtime/string_functions.h
  tests/phpt/string_functions/001_strip_tags_7_4.php
  tests/phpt/string_functions/002_substr_replace.php
  tests/phpt/string_functions/003_strip_tags_mixed_arg.php
Labels: PHP7.4, enhancement

#148 Run async PHP script in job workers
  common/php-functions.h
  compiler/code-gen/declarations.cpp
  compiler/code-gen/declarations.h
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  compiler/pipes/final-check.cpp
  functions.txt
  net/net-connections.cpp
  net/net-connections.h
  runtime/allocator.cpp
  runtime/allocator.h
  runtime/class_instance_decl.inl
  runtime/instance-copy-processor.cpp
  runtime/instance-copy-processor.h
  runtime/interface.cpp
  runtime/job-workers-interface.cpp
  runtime/job-workers-interface.h
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  runtime/job-workers/job-interface.cpp
  runtime/job-workers/job-interface.h
  runtime/job-workers/processing-jobs.cpp
  runtime/job-workers/processing-jobs.h
  runtime/job-workers/server-functions.cpp
  runtime/job-workers/server-functions.h
  runtime/job-workers/shared-memory-manager.cpp
  runtime/job-workers/shared-memory-manager.h
  runtime/net_events.cpp
  runtime/refcountable_php_classes.h
  runtime/rpc.h
  runtime/runtime.cmake
  server/job-workers/job-stats.cpp
  server/job-workers/job-stats.h
  server/job-workers/job-worker-client.cpp
  server/job-workers/job-worker-client.h
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/job-workers/job.h
  server/job-workers/pending-jobs.cpp
  server/job-workers/pending-jobs.h
  server/job-workers/shared-context.cpp
  server/job-workers/shared-context.h
  server/job-workers/shared-memory-manager.cpp
  server/job-workers/shared-memory-manager.h
  server/php-engine.cpp
  server/php-engine.h
  server/php-master.cpp
  server/php-queries.cpp
  server/php-queries.h
  server/php-query-data.cpp
  server/php-query-data.h
  server/php-worker.cpp
  server/php-worker.h
  server/server.cmake
Labels: enhancement, help wanted, refactoring

#154 Fix wait_net timeout for kphp_job_worker_wait().
  runtime/job-workers/client-functions.cpp
Labels: bug

#158 fix processing SQL and MC net answers in job workers
  common/tl/compiler/tl-compiler.cpp
  runtime/interface.cpp
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/job-interface.cpp
  runtime/job-workers/job-interface.h
  runtime/job-workers/job-message.h
  runtime/job-workers/processing-jobs.cpp
  runtime/job-workers/processing-jobs.h
  runtime/job-workers/server-functions.cpp
  runtime/job-workers/server-functions.h
  runtime/job-workers/shared-memory-manager.cpp
  runtime/job-workers/shared-memory-manager.h
  runtime/net_events.cpp
  runtime/tl/tl_builtins.h
  server/job-workers/job-worker-client.cpp
  server/job-workers/job-worker-client.h
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/job-workers/job.h
  server/job-workers/pipe-io.cpp
  server/job-workers/pipe-io.h
  server/php-engine.cpp
  server/php-engine.h
  server/php-queries.cpp
  server/php-queries.h
  server/php-query-data.h
  tests/python/lib/file_utils.py
  tests/python/lib/testcase.py
  tests/python/tests/compiler/test_global_vars_memory_stats.py
  tests/python/tests/composer/test_composer.py
  tests/python/tests/job_workers/php/X2Request.php
  tests/python/tests/job_workers/php/X2Response.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/index.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_cpu_job.py
  tests/python/tests/job_workers/test_job_with_mc_requests.py
  tests/python/tests/job_workers/test_job_with_rpc_requests.py
Labels: bug, enhancement
