Repository VKCOM/kphp, pull requests merged in 2021-07, with the labels that each got.

#277 fix timeout message written from SIGALRM handler
  server/json-logger.cpp
  server/json-logger.h
  server/php-engine.cpp
  server/php-runner.cpp
  tests/python/tests/json_logs/test_timeouts.py
Labels: small fix

#270 Flex refactoring
  flex/flex.cmake
  flex/flex.cpp
  flex/flex.h
  flex/vk-flex-data.h
  runtime/vkext.cpp
  tests/cpp/runtime/flex-test.cpp
  tests/cpp/runtime/runtime-tests.cmake
  vkext/vkext-flex.cpp
  vkext/vkext-flex.h
Labels: refactoring

#275 Improve long queries monitoring
  runtime/job-workers/processing-jobs.cpp
  runtime/job-workers/processing-jobs.h
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  server/server-stats.cpp
  server/server-stats.h
  tests/python/lib/engine.py
Labels: enhancement

#271 Job workers: starting job from job workers
  functions.txt
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  server/job-workers/job-worker-client.cpp
  server/job-workers/job-worker-server.cpp
  server/job-workers/shared-memory-manager.h
  server/php-engine.cpp
  server/php-master.cpp
  tests/cpp/server/job-workers/shared-memory-manager-test.cpp
  tests/phpt/job_workers/1_interface_compilation.php
  tests/phpt/job_workers/2_shared_immutable_messages_basic_compilation.php
  tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/http_worker.php
  tests/python/tests/job_workers/php/X2Request.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/php/utils.php
  tests/python/tests/job_workers/test_job_inside_job.py
Labels: enhancement, help wanted

#274 Gracefully terminate on 'class not found' compile error
  compiler/pipes/register-variables.cpp
  tests/phpt/cl/192_access_to_undef_class.php
Labels: small fix

#268 replace checking for instanceof with type inference instead of assumptions
  compiler/pipes/final-check.cpp
  compiler/pipes/final-check.h
  compiler/pipes/transform-to-smart-instanceof.cpp
  compiler/pipes/transform-to-smart-instanceof.h
  tests/phpt/class_inheritance/122_istanceof_ok.php
  tests/phpt/class_inheritance/123_istanceof_fail.php
Labels: refactoring

#207 add trailing zeros for bcmul results
  runtime/bcmath.cpp
  tests/phpt/dl/483_bcmath.php
Labels: PHP7.4

#281 Job workers: send no reply
  functions.txt
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  server/job-workers/job-message.h
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/php-worker.cpp
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_job_errors.py
  tests/python/tests/job_workers/test_job_no_reply.py
Labels: enhancement

#284 Support --job-workers-shared-messages option.
  runtime/job-workers/client-functions.cpp
  server/job-workers/job-message.h
  server/job-workers/shared-memory-manager.cpp
  server/job-workers/shared-memory-manager.h
  server/php-engine.cpp
  tests/python/tests/job_workers/test_cpu_job.py
  tests/python/tests/job_workers/test_job_shared_messages.py
Labels: enhancement

#286 added support for separator in numeric literal
  compiler/debug.cpp
  compiler/gentree.cpp
  compiler/gentree.h
  compiler/lexer.cpp
  compiler/token.h
  compiler/utils/trie.h
  tests/cpp/compiler/lexer-test.cpp
  tests/phpt/numeric_literal_separator/001_numeric_literal_ok.php
  tests/phpt/numeric_literal_separator/002_numeric_literal_wrong_several_underscores.php
Labels: PHP7.4, enhancement

#269 add support of spread operator `(...$a)`
  compiler/gentree.cpp
  compiler/pipes/final-check.h
  compiler/pipes/gen-tree-postprocess.cpp
  compiler/pipes/gen-tree-postprocess.h
  functions.txt
  runtime/array_functions.h
  tests/phpt/spread/001_spread.php
  tests/phpt/variadic_args/104_unpacking_in_wrong_place_1.php
  tests/phpt/variadic_args/105_unpacking_in_wrong_place_2.php
Labels: PHP7.4, enhancement
