Repository VKCOM/kphp, pull requests merged in 2021-12, with the labels that each got.

#368 use relative file names in hashes/codegen/exceptions
  .idea/encodings.xml
  compiler/code-gen/code-generator.cpp
  compiler/code-gen/code-generator.h
  compiler/code-gen/files/vars-cpp.cpp
  compiler/code-gen/vertex-compiler.cpp
  compiler/code-gen/writer-data.cpp
  compiler/compiler-core.cpp
  compiler/data/function-data.cpp
  compiler/data/lambda-interface-generator.cpp
  compiler/data/src-file.h
  compiler/debug.cpp
  compiler/gentree.cpp
  compiler/lexer.cpp
  compiler/pipes/analyze-performance.cpp
  compiler/pipes/gen-tree-postprocess.cpp
  compiler/pipes/preprocess-exceptions.cpp
  compiler/pipes/resolve-self-static-parent.cpp
  compiler/stage.cpp
  compiler/token.h
  tests/phpt/cl/162_mix_class_and_null.php
  tests/phpt/dl/964_try.php
  tests/phpt/exceptions/07_error_methods.php
  tests/phpt/exceptions/08_exception_methods.php
  tests/phpt/exceptions/12_throwable_methods.php
  tests/phpt/exceptions/inheritance/02_access_inherited_props.php
  tests/phpt/exceptions/inheritance/03_catch_derived_interface.php
  tests/phpt/exceptions/inheritance/04_catch_throwable.php
  tests/phpt/exceptions/inheritance/05_catch_throwable2.php
  tests/phpt/exceptions/inheritance/13_custom_ctor.php
  tests/phpt/exceptions/inheritance/14_default_ctor.php
  tests/phpt/exceptions/inheritance/16_inner_outer.php
  tests/phpt/exceptions/inheritance/24_throw_error.php
  tests/phpt/exceptions/inheritance/33_throw_throwable.php
  tests/phpt/exceptions/inheritance/37_with_implements.php
  tests/phpt/exceptions/inheritance/38_with_implements2.php
  tests/phpt/exceptions/inheritance/39_with_implements3.php
  tests/phpt/exceptions/multicatch/01_catch_interface.php
  tests/phpt/fork/012_exceptions.php
Labels: refactoring

#373 Implement visitors for builtin Exception class
  runtime/exception.h
Labels: small fix

#371 Use inheritance and virtual methods instead of C-style manual emulation in php queries
  server/php-engine.cpp
  server/php-queries-types.cpp
  server/php-queries-types.h
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  server/php-worker.cpp
  server/php-worker.h
  server/server.cmake
Labels: refactoring

#341 fixed gmmktime function work
  runtime/datetime.cpp
Labels: bug

#377 support compilation for Apple M1 Silicon
  .clang-tidy
  .lldbinit
  cmake/init-compilation-flags.cmake
  cmake/init-global-vars.cmake
  cmake/popular-common.cmake
  common/algorithms/simd-int-to-string.h
  common/common.cmake
  common/cpuid.cpp
  common/cpuid.h
  common/crc32_arm64.cpp
  common/crc32c_arm64.cpp
  common/crypto/aes256-arm64.cpp
  common/crypto/aes256-arm64.h
  common/crypto/aes256-test.cpp
  common/crypto/aes256.cpp
  common/server/crash-dump.cpp
  common/server/crash-dump.h
  common/server/signals.cpp
  compiler/compiler-settings.cpp
  compiler/stage.cpp
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
  server/php-runner.cpp
  server/php-runner.h
  server/ucontext-portable.h
  tests/phpt/ffi/typing/034_nonexisting_func_call_error3.php
  tests/tests.cmake
  vkext/vk_zend.h
  vkext/vkext.cmake
  vkext/vkext.cpp
Labels: documentation, enhancement, help wanted

#384 fixed `string::try_to_float_as_php8` function
  runtime/string.inl
  tests/kphp_tester.py
  tests/phpt/migration_php8/009_blank_no_warning.php
Labels: bug, PHP8

#382 Added Statshouse client for sending metrics to it
  common/tl/constants/statshouse.h
  common/tl/parse.cpp
  server/php-engine.cpp
  server/php-master.cpp
  server/server.cmake
  server/statshouse/add-metrics-batch.cpp
  server/statshouse/add-metrics-batch.h
  server/statshouse/statshouse-client.cpp
  server/statshouse/statshouse-client.h
Labels: enhancement

#389 zstd now compress at zero level
  runtime/zstd.cpp
  tests/phpt/zstd/1_compress.php
Labels: small fix

#392 [common] refactor common stats
  common/server/stats.cpp
  common/server/stats.h
  common/server/statsd-client.cpp
  common/server/tl-stats-t.h
  common/stats/provider.cpp
  common/stats/provider.h
  server/php-master.cpp
Labels: refactoring

#391 Use `std::variant` in `net_events` and `net_queries` instead of self-made union based struct
  common/wrappers/overloaded.h
  runtime/net_events.cpp
  server/php-engine.cpp
  server/php-queries.cpp
  server/php-queries.h
  server/php-worker.cpp
Labels: refactoring

#379 add support of 'flags' argument array_unique() function
  builtin-functions/_functions.txt
  runtime/array_functions.h
  tests/phpt/array/017_array_unique.php
  tests/zend-test-list
Labels: enhancement

#378 implement array_merge_recursive()
  builtin-functions/_functions.txt
  runtime/array.inl
  runtime/array_decl.inl
  runtime/array_functions.h
  tests/phpt/array/016_array_merge_recursive.php
  tests/zend-test-list
Labels: enhancement
