Repository VKCOM/kphp, pull requests merged in 2021-06, with the labels that each got.

#255 Fix job timeout test.
  tests/python/lib/testcase.py
  tests/python/tests/job_workers/test_job_errors.py
Labels: small fix

#263 increase timeout in job worker errors test to make it stable
  tests/python/tests/job_workers/php/http_worker.php
Labels: small fix

#260 Add absent math constants
  compiler/debug.cpp
  compiler/gentree.cpp
  compiler/keywords.gperf
  compiler/token.h
  functions.txt
  tests/phpt/dl/1028_math_constants.php
  tests/phpt/dl/1029_inf.php
Labels: small fix

#247 added str_ireplace function
  functions.txt
  runtime/string_functions.cpp
  runtime/string_functions.h
  tests/phpt/string_functions/003_str_ireplace.php
Labels: enhancement

#250 added optimization for (v)sprintf call with simple format
  compiler/compiler.cmake
  compiler/compiler.cpp
  compiler/pipes/convert-sprintf-calls.cpp
  compiler/pipes/convert-sprintf-calls.h
  tests/phpt/dl/1025_fail_sprintf_dollar_sign.php
  tests/phpt/dl/1025_sprintf_dollar_sign.php
  tests/phpt/dl/976_sprintf.php
  tests/phpt/sprintf/001_sprintf.php
  tests/phpt/sprintf/002_vprintf.php
Labels: enhancement

#264 Precompute hashes for isset() and unset()
  compiler/code-gen/vertex-compiler.cpp
  runtime/array.inl
  runtime/array_decl.inl
  runtime/mixed.inl
  runtime/mixed_decl.inl
Labels: optimization

#257 Job workers: shared immutable messages
  compiler/code-gen/declarations.cpp
  compiler/code-gen/declarations.h
  compiler/code-gen/naming.h
  compiler/compiler-core.h
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  compiler/pipes/final-check.cpp
  functions.txt
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  runtime/job-workers/job-interface.h
  runtime/job-workers/server-functions.cpp
  server/job-workers/job-message.h
  server/job-workers/job-worker-server.cpp
  server/job-workers/shared-memory-manager.cpp
  server/job-workers/shared-memory-manager.h
  tests/cpp/server/job-workers/shared-memory-manager-test.cpp
  tests/phpt/job_workers/2_shared_immutable_messages_basic_compilation.php
  tests/phpt/job_workers/3_mutable_shared_memory_piece.php
  tests/phpt/job_workers/4_not_single_shared_memory_piece_member.php
  tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/SharedMemoryData.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/SumJobRequestWithSharedData.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/SumJobRequestWithoutSharedData.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/SumJobResponse.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/http_worker.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/job_worker.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_job_resumable.py
  tests/python/tests/job_workers/test_job_shared_immutable_message.py
  tests/python/tests/job_workers/test_job_worker_wakeup.py
Labels: enhancement, help wanted

#226 rewrite ClassData::get_instance_method()
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  tests/phpt/regress/issue215/test1.php
  tests/phpt/regress/issue215/test2.php
  tests/phpt/regress/issue215/test3.php
Labels: refactoring

#259 Stats into shared memory
  common/stats/provider.h
  common/wrappers/madvise.h
  common/wrappers/memory-utils.h
  net/net-aes-keys.cpp
  net/net-connections.cpp
  net/net-connections.h
  net/net-crypto-aes.cpp
  net/net.cmake
  runtime/confdata-global-manager.cpp
  runtime/instance-cache.cpp
  runtime/inter-process-resource.h
  runtime/job-workers/client-functions.cpp
  runtime/rpc.cpp
  server/job-workers/job-stats.cpp
  server/job-workers/job-stats.h
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/job-workers/job-workers-context.h
  server/job-workers/shared-memory-manager.cpp
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-master-restart.cpp
  server/php-master.cpp
  server/php-master.h
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  server/php-worker-stats.cpp
  server/php-worker-stats.h
  server/php-worker.cpp
  server/server-stats.cpp
  server/server-stats.h
  server/server.cmake
  tests/python/lib/testcase.py
  tests/python/tests/http_server/test__simple_scenario_example.py
  tests/python/tests/job_workers/test_complex_scenario_job.py
  tests/python/tests/job_workers/test_cpu_job.py
  tests/python/tests/job_workers/test_job_errors.py
  tests/python/tests/job_workers/test_job_resumable.py
  tests/python/tests/job_workers/test_job_shared_immutable_message.py
  tests/python/tests/stats/test_percentile_smoke.py
Labels: enhancement, help wanted, refactoring

#267 Add missing stats
  server/php-master.cpp
  server/server-stats.cpp
  tests/python/tests/stats/php/index.php
  tests/python/tests/stats/test_master_stats.py
Labels: bug
