Repository VKCOM/kphp, pull requests merged in 2021-04, with the labels that each got.

#156 Allow exit in forks & don't wait forks after exit.
  compiler/code-gen/files/init-scripts.cpp
  compiler/pipes/final-check.cpp
  runtime/interface.cpp
  runtime/interface.h
  server/php-runner.cpp
  tests/phpt/fork/017_exit_from_fork.php
  tests/phpt/fork/017_exit_in_resumable_error.php
  tests/phpt/fork/018_die_in_resumable_error.php
  tests/phpt/fork/018_exit_from_fork.php
  tests/phpt/fork/024_wait_all_forks_on_finish_with_main_exit.php
Labels: bug, enhancement

#157 Support performance inspections enabling for classes
  compiler/data/performance-inspections.cpp
  compiler/data/performance-inspections.h
  compiler/pipes/analyze-performance.cpp
  compiler/pipes/parse-and-apply-phpdoc.cpp
  tests/cpp/compiler/data/performance-inspections-test.cpp
  tests/phpt/performance_inspections/13_warn_tag_for_class.php
  tests/phpt/performance_inspections/14_warn_tag_for_interface.php
  tests/phpt/performance_inspections/7_array_reserve_warn.php
  tests/phpt/performance_inspections/8_array_reserve_no_warn.php
Labels: enhancement

#159 Increase http server limits.
  net/net-http-server.cpp
  net/net-http-server.h
  server/php-engine.cpp
  tests/python/tests/http_server/php/index.php
  tests/python/tests/http_server/test_request_limits.py
Labels: enhancement

#164 Implement zstd api.
  .github/workflows/Dockerfile.buster
  .github/workflows/Dockerfile.focal
  common/smart_ptrs/unique_ptr_with_delete_function.h
  functions.txt
  runtime/runtime.cmake
  runtime/zstd.cpp
  runtime/zstd.h
  tests/cpp/runtime/runtime-tests.cmake
  tests/cpp/runtime/zstd-test.cpp
  tests/kphp_tester.py
  tests/phpt/zstd/1_compress.php
  tests/phpt/zstd/2_uncompress.php
  tests/phpt/zstd/3_compress_uncompress.php
  tests/python/tests/http_server/php/index.php
  tests/python/tests/http_server/test_zstd.py
Labels: enhancement

#173 Improve backtrace experience
  common/smart_ptrs/intrusive_ptr.h
  runtime/array_decl.inl
  runtime/mixed.cpp
  runtime/mixed.inl
  runtime/mixed_decl.inl
  runtime/runtime.cmake
  runtime/string.cpp
  runtime/string.inl
  runtime/string_decl.inl
Labels: enhancement

#175 fix `preg_match($pat, $s)` overloading
  runtime/regexp.cpp
  tests/phpt/regexp/005_regexp_match2.php
Labels: enhancement, help wanted

#165 Job workers: timeouts & resumable
  compiler/code-gen/files/type-tagger.cpp
  functions.txt
  net/net-tcp-rpc-common.h
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  runtime/job-workers/job-interface.cpp
  runtime/job-workers/job-interface.h
  runtime/job-workers/job-message.h
  runtime/job-workers/processing-jobs.cpp
  runtime/job-workers/processing-jobs.h
  runtime/net_events.cpp
  runtime/net_events.h
  runtime/resumable.cpp
  runtime/rpc.cpp
  server/job-workers/job-worker-client.cpp
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  server/php-worker.cpp
  tests/cpp/runtime/_runtime-tests-env.cpp
  tests/python/tests/job_workers/__init__.py
  tests/python/tests/job_workers/php/ComplexScenario/CollectStatsJobRequest.php
  tests/python/tests/job_workers/php/ComplexScenario/CollectStatsJobResponse.php
  tests/python/tests/job_workers/php/ComplexScenario/NetPid.php
  tests/python/tests/job_workers/php/ComplexScenario/StatTraits.php
  tests/python/tests/job_workers/php/ComplexScenario/Stats.php
  tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
  tests/python/tests/job_workers/php/ComplexScenario/_job_scenario.php
  tests/python/tests/job_workers/php/ComplexScenario/_stats_processor.php
  tests/python/tests/job_workers/php/X2Request.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_complex_scenario_job.py
  tests/python/tests/job_workers/test_job_errors.py
  tests/python/tests/job_workers/test_job_resumable.py
Labels: enhancement

#160 Replace histogram -> gauge stats.
  common/stats/provider.cpp
  common/stats/provider.h
  runtime/memory_resource/memory_resource.cpp
  server/cluster-name.cpp
  server/cluster-name.h
  server/confdata-stats.cpp
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-master.cpp
  server/php-worker-stats.cpp
  server/server.cmake
  tests/cpp/server/cluster-name-test.cpp
  tests/cpp/server/server-tests.cmake
  tests/python/lib/stats_receiver.py
Labels: enhancement

#86 implement strtotime() via timelib to make it identical to PHP strtotime()
  .github/workflows/Build.yml
  .github/workflows/Dockerfile.buster
  .github/workflows/Dockerfile.focal
  CMakeLists.txt
  cmake/external-libraries.cmake
  compiler/compiler-settings.cpp
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
  docs/kphp-language/kphp-vs-php/kphp-vs-php-differences.md
  runtime/datetime.cpp
  runtime/interface.cpp
  runtime/runtime.cmake
  runtime/timelib_wrapper.cpp
  runtime/timelib_wrapper.h
  tests/phpt/dl/459_strtotime.php
  tests/phpt/dl/484_strftime.php
  tests/phpt/pk/029_date_default_timezone_get.php
  tests/phpt/timelib/checkdate.php
  tests/phpt/timelib/strtotime.php
  tests/phpt/timelib/strtotime_relative.php
Labels: enhancement

#181 do nothing on job worker server connection close
  net/net-connections.cpp
  net/net-connections.h
  server/job-workers/job-worker-server.cpp
Labels: bug

#178 More memory stat.
  common/dl-utils-lite.cpp
  common/dl-utils-lite.h
  common/macos-ports.h
  compiler/stats.cpp
  runtime/instance-cache.cpp
  server/php-engine.cpp
  server/php-master.cpp
  server/php-runner.cpp
  server/php-worker-stats.cpp
  server/php-worker-stats.h
Labels: enhancement

#190 Job workers: improve interface
  functions.txt
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  tests/python/tests/job_workers/php/ComplexScenario/_http_scenario.php
  tests/python/tests/job_workers/php/http_worker.php
Labels: enhancement

#183 docs: add missing bits about timelib dependency
  docs/_config.yml
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
Labels: documentation

#182 make preg_quote escape '#' sign
  runtime/regexp.cpp
  tests/phpt/dl/496_regex.php
  tests/phpt/regexp/006_preg_quote.php
  tests/zend-test-list
Labels: PHP7.4

#199 Move python tests in separate dir
  .idea/misc.xml
  tests/.gitignore
  tests/python/lib/testcase.py
Labels: refactoring

#197 fix passing lambdas through variables
  compiler/pipes/preprocess-function.cpp
  tests/phpt/lambdas/047_typed_lambda_through_var.php
Labels: bug

#188 Fix self unknown this
  compiler/pipes/resolve-self-static-parent.cpp
  tests/phpt/cl/180_fail_self_in_static_methods.php
Labels: bug

#200 fix compilation error when typed lambda is declared but not used
  compiler/pipes/preprocess-function.cpp
  tests/phpt/lambdas/048_unknown_lambda.php
Labels: bug

#195 remove a redundant error from parsing lambdas
  compiler/gentree.cpp
  compiler/stage.cpp
  compiler/stage.h
  tests/kphp_tester.py
  tests/phpt/parse_errors/fail_without_error_from_lambda.php
Labels: bug

#202 remove unused fix_php_bugs flag from the regexp module
  runtime/regexp.cpp
  runtime/regexp.h
Labels: refactoring

#205 mark long2ip argument type as int
  functions.txt
  runtime/interface.h
  tests/phpt/declare/03_strict_types_error.php
  tests/phpt/declare/03_strict_types_error.php.inc
Labels: small fix

#203 respect `OFFSET_CAPTURE` when padding preg_match_all() results
  runtime/regexp.cpp
  tests/phpt/dl/496_regex.php
  tests/phpt/regexp/007_preg_offset_capture_padding.php
Labels: PHP7.4

#193 Job workers memory refactoring
  common/stats/provider.h
  compiler/class-assumptions.cpp
  functions.txt
  runtime/instance-copy-processor.cpp
  runtime/instance-copy-processor.h
  runtime/inter-process-resource.h
  runtime/interface.cpp
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/client-functions.h
  runtime/job-workers/job-interface.cpp
  runtime/job-workers/job-interface.h
  runtime/job-workers/job-message.h
  runtime/job-workers/processing-jobs.cpp
  runtime/job-workers/processing-jobs.h
  runtime/job-workers/server-functions.cpp
  runtime/job-workers/shared-memory-manager.cpp
  runtime/job-workers/shared-memory-manager.h
  runtime/memory_resource/extra-memory-pool.h
  runtime/memory_resource/unsynchronized_pool_resource.cpp
  runtime/memory_resource/unsynchronized_pool_resource.h
  runtime/php_assert.cpp
  runtime/runtime.cmake
  runtime/string.inl
  runtime/string_decl.inl
  server/job-workers/job-message.h
  server/job-workers/job-stats.cpp
  server/job-workers/job-stats.h
  server/job-workers/job-worker-client.cpp
  server/job-workers/job-worker-server.cpp
  server/job-workers/job-worker-server.h
  server/job-workers/shared-memory-manager.cpp
  server/job-workers/shared-memory-manager.h
  server/php-engine.cpp
  server/php-master.cpp
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-worker.cpp
  server/server.cmake
  tests/cpp/runtime/memory_resource/extra-memory-pool-test.cpp
  tests/cpp/runtime/runtime-tests.cmake
  tests/cpp/server/job-workers/shared-memory-manager-test.cpp
  tests/cpp/server/server-tests.cmake
  tests/python/lib/engine.py
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/index.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_complex_scenario_job.py
  tests/python/tests/job_workers/test_cpu_job.py
  tests/python/tests/job_workers/test_job_errors.py
  tests/python/tests/job_workers/test_job_resumable.py
Labels: enhancement, help wanted, refactoring

#208 Job workers: graceful termination
  server/job-workers/job-worker-server.cpp
  server/php-engine.cpp
  server/php-master.cpp
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_job_graceful_termination.py
Labels: enhancement

#209 Implement null coalesce via class.
  compiler/code-gen/vertex-compiler.cpp
  runtime/null_coalesce.h
Labels: bug, refactoring

#133 Fix race condition in task (lease) communication protocol
  common/tl/constants/kphp.h
  server/lease-config-parser.cpp
  server/lease-context.h
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-lease.cpp
  server/php-lease.h
Labels: bug, enhancement

#204 improve stacktrace on type mismatch when variable reassigning occurs
  compiler/inferring/restriction-stacktrace-finder.cpp
  tests/phpt/stacktrace/10_stacktrace.php
  tests/phpt/stacktrace/11_stacktrace.php
Labels: bug, small fix

#196 drop wait() edges from a call graph of calculating bad vars
  compiler/pipes/calc-bad-vars.cpp
Labels: help wanted, small fix

#220 Introduce job workers ratio option
  common/kprintf.cpp
  common/options.cpp
  common/options.h
  common/tl2php/tl2php.cpp
  compiler/kphp2cpp.cpp
  runtime/inter-process-resource.h
  runtime/interface.cpp
  runtime/job-workers/job-interface.cpp
  server/confdata-binlog-replay.cpp
  server/job-workers/job-worker-client.cpp
  server/job-workers/job-workers-context.h
  server/job-workers/pipe-io.cpp
  server/job-workers/shared-memory-manager.cpp
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-master-restart.cpp
  server/php-master-restart.h
  server/php-master-warmup.h
  server/php-master.cpp
  server/server-log.cpp
  server/server-log.h
  server/server.cmake
  server/workers-control.cpp
  server/workers-control.h
  tests/cpp/runtime/_runtime-tests-env.cpp
  tests/cpp/runtime/inter-process-resource-test.cpp
  tests/cpp/server/job-workers/shared-memory-manager-test.cpp
  tests/cpp/server/server-tests.cmake
  tests/cpp/server/workers-control-test.cpp
  tests/python/tests/job_workers/test_complex_scenario_job.py
  tests/python/tests/job_workers/test_cpu_job.py
  tests/python/tests/job_workers/test_job_errors.py
  tests/python/tests/job_workers/test_job_graceful_termination.py
  tests/python/tests/job_workers/test_job_resumable.py
  tests/python/tests/job_workers/test_job_with_mc_requests.py
  tests/python/tests/job_workers/test_job_with_rpc_requests.py
Labels: enhancement, refactoring

#135 optimize cfg, uninited and smart casts
  .lldbinit
  compiler/data/data_ptr.h
  compiler/data/vertex-adaptor.h
  compiler/inferring/ifi.h
  compiler/pipes/cfg-end.cpp
  compiler/pipes/cfg.cpp
  compiler/pipes/function-and-cfg.h
  compiler/utils/dsu.h
  compiler/utils/idgen.h
  compiler/utils/idmap.h
  compiler/vertex-meta_op_base.h
  compiler/vertex.h
  tests/phpt/dl/952_cfg.php
  tests/phpt/dl/952_cfg_uninited.php
  tests/phpt/smart_casts/01_basic.php
  tests/phpt/smart_casts/05_inside_operators.php
Labels: optimization

#137 optimize CodeGenF::on_finish() performed in a single thread
  compiler/code-gen/files/init-scripts.cpp
  compiler/code-gen/files/init-scripts.h
  compiler/code-gen/files/tl2cpp/tl2cpp.cpp
  compiler/code-gen/files/tl2cpp/tl2cpp.h
  compiler/compiler-core.cpp
  compiler/compiler-core.h
  compiler/data/function-data.cpp
  compiler/data/function-data.h
  compiler/pipes/code-gen.cpp
  compiler/pipes/code-gen.h
Labels: optimization

#136 optimize bad_vars calculation performed in a single thread
  compiler/data/function-data.h
  compiler/data/var-data.h
  compiler/pipes/calc-bad-vars.cpp
  compiler/pipes/calc-func-dep.cpp
  compiler/pipes/calc-func-dep.h
  compiler/pipes/check-ub.cpp
  tests/phpt/warnings/1_ub_foreach_var_trycatch.php
  tests/phpt/warnings/2_ub_foreach_var_trycatch2.php
  tests/phpt/warnings/3_ub_var_trycatch.php
  tests/phpt/warnings/5_ub_globals.php
Labels: optimization

#221 explicitly forbid to call `kphp_job_worker_start()` from job workers
  runtime/job-workers/client-functions.cpp
  server/job-workers/job-worker-client.h
Labels: enhancement

#189 Function colors and palette
  compiler/compiler-core.h
  compiler/compiler.cmake
  compiler/compiler.cpp
  compiler/data/class-data.cpp
  compiler/data/function-data.h
  compiler/function-colors.cpp
  compiler/function-colors.h
  compiler/phpdoc.cpp
  compiler/phpdoc.h
  compiler/pipes/calc-bad-vars.cpp
  compiler/pipes/parse-and-apply-phpdoc.cpp
  compiler/pipes/register-kphp-configuration.cpp
  compiler/pipes/register-kphp-configuration.h
  tests/phpt/colors/000_highload.php
  tests/phpt/colors/001_allowed.php
  tests/phpt/colors/002_not_allowed.php
  tests/phpt/colors/003_not_allowed_message_internals.php
  tests/phpt/colors/004_not_allowed_api_curl.php
  tests/phpt/colors/005_not_allowed_ssr_db.php
  tests/phpt/colors/006_complex_ok.php
  tests/phpt/colors/007_complex_fail.php
  tests/phpt/colors/008_cross_cals.php
  tests/phpt/colors/009_two_error_in_subtree.php
  tests/phpt/colors/010_allowed_in_cross_calls.php
  tests/phpt/colors/011_error_with_different_caller.php
  tests/phpt/colors/012_recursive_call.php
  tests/phpt/colors/013_almost_same_rules.php
  tests/phpt/colors/014_not_allowed_more.php
  tests/phpt/colors/015_colored_resumable.php
  tests/phpt/colors/016_colored_resumable_2.php
  tests/phpt/colors/017_colored_recursive.php
  tests/phpt/colors/018_colored_recursive_2.php
  tests/phpt/colors/019_emulate_cuf.php
  tests/phpt/colors/020_different_paths.php
  tests/phpt/colors/021_different_paths_ok.php
  tests/phpt/colors/022_long_path.php
Labels: enhancement, help wanted

#224 fix including lib headers of extern functions imported from libs (txt files)
  compiler/pipes/calc-func-dep.cpp
  compiler/pipes/code-gen.cpp
Labels: bug
