Repository VKCOM/kphp, pull requests merged in 2021-09, with the labels that each got.

#297 increase mysql log message verbosity
  server/php-engine.cpp
Labels: small fix

#305 [github] fix mac os build
  .github/workflows/Build.yml
Labels: small fix

#299 fixed `parse_str` behavior with empty or `null` string
  runtime/url.cpp
  tests/phpt/dl/481_parse_str_with_empty_string.php
Labels: bug

#306 Expose job error codes
  functions.txt
Labels: small fix

#304 Try to fix SIGSEGV in job workers
  runtime/allocator.cpp
  runtime/allocator.h
  runtime/array.inl
  runtime/instance-cache.cpp
  runtime/instance-copy-processor.h
  server/job-workers/job-worker-server.cpp
Labels: bug

#301 fix SIGSEGV on TL Dictionary keys serialization in case of numeric strings
  runtime/tl/tl_builtins.h
Labels: bug

#298 added runtime migration warnings for numeric strings and string-number comparison
  functions.txt
  runtime/comparison_operators.inl
  runtime/interface.cpp
  runtime/migration_php8.cpp
  runtime/migration_php8.h
  runtime/mixed.inl
  runtime/runtime.cmake
  runtime/string.inl
  runtime/string_decl.inl
  tests/cpp/runtime/number-string-comparison.cpp
  tests/cpp/runtime/runtime-tests.cmake
  tests/kphp_tester.py
  tests/phpt/migration_php8/001_inf.php
  tests/phpt/migration_php8/002_string_number_comparison.php
  tests/phpt/migration_php8/003_string_number_comparison_array_func.php
  tests/phpt/migration_php8/004_string_number_comparison_enable_disable.php
  tests/phpt/migration_php8/005_explicit_cast.php
  tests/phpt/migration_php8/006_is_numeric.php
  tests/phpt/migration_php8/007_string_string_comparison.php
  tests/phpt/migration_php8/008_string_number_spaceship.php
  tests/python/lib/kphp_builder.py
  tests/python/lib/kphp_run_once.py
Labels: PHP8

#311 [build] add new functions.txt files to deb-package
  CMakeLists.txt
Labels: bug

#316 fixed `parse_str` behavior
  runtime/url.cpp
  tests/phpt/dl/481_parse_str_with_empty_string.php
Labels: bug

#315 Implement function for disabling json log on timeout
  functions.txt
  runtime/interface.cpp
  runtime/interface.h
  server/php-runner.cpp
Labels: enhancement
