Repository VKCOM/kphp, pull requests merged in 2021-02, with the labels that each got.

#125 fix race condition "called do_recalc on finished inferer"
  compiler/pipes/optimization.cpp
Labels: bug

#104 Task workers: Step 1 - basic design
  common/type_traits/is_copyable.h
  functions.txt
  runtime/interface.cpp
  runtime/net_events.cpp
  runtime/runtime.cmake
  runtime/task-workers-interface.cpp
  runtime/task-workers-interface.h
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-master-restart.cpp
  server/php-master-restart.h
  server/php-master-warmup.h
  server/php-master.cpp
  server/php-queries.cpp
  server/php-queries.h
  server/server.cmake
  server/task-workers/pending-tasks.cpp
  server/task-workers/pending-tasks.h
  server/task-workers/pipe-io.cpp
  server/task-workers/pipe-io.h
  server/task-workers/shared-context.cpp
  server/task-workers/shared-context.h
  server/task-workers/shared-memory-manager.cpp
  server/task-workers/shared-memory-manager.h
  server/task-workers/task-worker-client.cpp
  server/task-workers/task-worker-client.h
  server/task-workers/task-worker-server.cpp
  server/task-workers/task-worker-server.h
  server/task-workers/task-workers-context.cpp
  server/task-workers/task-workers-context.h
  server/task-workers/task.h
Labels: enhancement

#113 Move instance deep copy logic from instance cache
  compiler/code-gen/declarations.cpp
  runtime/class_instance.inl
  runtime/class_instance_decl.inl
  runtime/instance-cache.cpp
  runtime/instance-cache.h
  runtime/instance-copy-processor.cpp
  runtime/instance-copy-processor.h
  runtime/instance_cache.h
  runtime/interface.cpp
  runtime/memory_usage.h
  runtime/runtime.cmake
  server/php-master.cpp
Labels: refactoring

#128 fix closing uninited pipe file descriptors on task worker client init
  server/php-engine.cpp
  server/task-workers/task-worker-client.cpp
  server/task-workers/task-worker-server.cpp
  server/task-workers/task-workers-context.cpp
  server/task-workers/task-workers-context.h
Labels: bug

#129 Copy val_ref_flag for extracted resumable expressions.
  compiler/pipes/extract-resumable-calls.cpp
  tests/phpt/fork/022_wait_all_forks_on_finish.php
  tests/phpt/fork/023_op_set_in_resumable_expr.php
Labels: bug

#130 improve preg_replace and preg_replace_callback typing
  functions.txt
  runtime/regexp.h
  tests/phpt/regexp/001_string_result.php
  tests/phpt/regexp/002_null_error.php
Labels: enhancement
