Repository VKCOM/kphp, pull requests merged in 2021-11, with the labels that each got.

#353 add critical section for xgboost library
  runtime/xgboost/model.cpp
Labels: small fix

#354 fix that ctrl+c stopped working on compilation stage
  compiler/make/make.cpp
Labels: bug

#338 added compile-time error about undefined constant
  compiler/pipes/inline-defines-usages.cpp
  functions.txt
  tests/phpt/constants/001_undefined.php
Labels: enhancement

#361 Move functions*.txt files to separate folder
  CMakeLists.txt
  builtin-functions/_functions.txt
  builtin-functions/ffi.txt
  builtin-functions/spl.txt
  builtin-functions/uberh3.txt
  compiler/kphp2cpp.cpp
  docs/_config.yml
Labels: enhancement

#352 Rework tracking references to the same instances on copying
  compiler/code-gen/declarations.cpp
  runtime/instance-copy-processor.h
  runtime/job-workers/job-interface.h
  runtime/refcountable_php_classes.h
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/JobRequest.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/JobResponse.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/SharedMemoryContext.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/SomeContext.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/http_worker.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/job_worker.php
  tests/python/tests/job_workers/php/http_worker.php
  tests/python/tests/job_workers/php/job_worker.php
  tests/python/tests/job_workers/test_job_shared_immutable_message.py
Labels: bug, enhancement

#363 added `JSON_PRETTY_PRINT` constant to `_functions.txt`
  builtin-functions/_functions.txt
  compiler/pipes/inline-defines-usages.cpp
  runtime/json-functions.h
Labels: small fix
