Repository VKCOM/kphp, pull requests merged in 2022-02, with the labels that each got.

#426 [vkext] return empty array instead of false in `rpc_tl_query` and `typed_rpc_tl_query`
  tests/kphp_ci_pipeline_runner.py
  vkext/vkext-schema-memcache.cpp
  vkext/vkext.cmake
Labels: small fix

#427 Add str_starts_with() and str_ends_with() functions
  builtin-functions/_functions.txt
  runtime/string.inl
  runtime/string_decl.inl
  runtime/string_functions.cpp
  runtime/string_functions.h
  tests/cpp/runtime/string-test.cpp
Labels: small fix, PHP8

#440 enable using pch in _loader_instantiations{i}.cpp translation units
  compiler/code-gen/files/type-tagger.cpp
Labels: small fix

#432 Improved error handling in master process
  common/dl-utils-lite.cpp
  server/php-master.cpp
Labels: small fix

#423 Forbid to pass resumable lambdas to builtin functions
  compiler/pipes/final-check.cpp
  tests/phpt/fork/030_fail_pass_resumable_lambda_to_builtin_function.php
  tests/phpt/fork/031_ok_pass_fork_unreachable_resumable_lambda_to_builtin_function.php
Labels: bug

#411 fix bug in less than array operator
  runtime/comparison_operators.inl
  tests/phpt/dl/1034_array_lt.php
Labels: bug

#437 better behavior on phpdoc inheritance and "phpdoc + type hint" combinations
  compiler/gentree.cpp
  compiler/pipes/generate-virtual-methods.cpp
  compiler/pipes/parse-and-apply-phpdoc.cpp
  tests/phpt/class_inheritance/049_deligating_constructor_kphp_infer.php
  tests/phpt/interfaces/signature_compatibility/callable_inherit_error.php
  tests/phpt/interfaces/signature_compatibility/callable_inherit_ok.php
  tests/phpt/interfaces/signature_compatibility/iface_return_derived.php
  tests/phpt/interfaces/signature_compatibility/multi_level_doc_inherit.php
  tests/phpt/phpdocs/027_type_hints_with_phpdocs.php
  tests/phpt/phpdocs/101_typehint_doc_mismatch_1.php
  tests/phpt/phpdocs/102_typehint_doc_mismatch_2.php
  tests/phpt/phpdocs/103_typehint_doc_mismatch_3.php
  tests/phpt/phpdocs/104_typehint_doc_mismatch_4.php
  tests/phpt/typehints/return_types/15_for_assumption.php
Labels: enhancement

#447 [common/tl] fix type deducing at `vk::tl::store_to_buffer`
  common/tl/methods/string.h
Labels: small fix

#438 speedup phpdoc parsing and store PhpDocComment instead of phpdoc_str
  common/algorithms/hashes.h
  compiler/class-assumptions.cpp
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  compiler/data/class-members.cpp
  compiler/data/class-members.h
  compiler/data/data_ptr.h
  compiler/data/function-data.h
  compiler/data/generics-mixins.cpp
  compiler/data/generics-mixins.h
  compiler/gentree.cpp
  compiler/gentree.h
  compiler/inferring/type-hint-recalc.cpp
  compiler/lambda-utils.cpp
  compiler/lexer.cpp
  compiler/lexer.h
  compiler/phpdoc.cpp
  compiler/phpdoc.h
  compiler/pipes/calc-locations.cpp
  compiler/pipes/check-classes.cpp
  compiler/pipes/check-tl-classes.cpp
  compiler/pipes/collect-required-and-classes.cpp
  compiler/pipes/parse-and-apply-phpdoc.cpp
  compiler/pipes/register-ffi-scopes.cpp
  compiler/pipes/resolve-self-static-parent.cpp
  compiler/pipes/sort-and-inherit-classes.cpp
  compiler/pipes/split-switch.cpp
  compiler/vertex-desc.json
  tests/cpp/compiler/phpdoc-test.cpp
Labels: optimization, refactoring

#442 sending raw stats to statshouse
  common/resolver.cpp
  common/server/statsd-client.cpp
  common/server/tl-stats-t.h
  common/stats/provider.h
  server/php-engine.cpp
  server/php-master.cpp
  server/server-stats.cpp
  server/server.cmake
  server/statshouse/add-metrics-batch.cpp
  server/statshouse/add-metrics-batch.h
  server/statshouse/statshouse-client.cpp
  server/statshouse/statshouse-client.h
  server/statshouse/worker-stats-buffer.cpp
  server/statshouse/worker-stats-buffer.h
Labels: enhancement

#419 Collect classes from @var phpdocs if they are unreachable from php code
  compiler/pipes/collect-required-and-classes.cpp
  tests/phpt/cl/030_resolve_from_phpdoc.php
Labels: bug
