Repository VKCOM/kphp, pull requests merged in 2022-11, with the labels that each got.

#669 eliminate deprecated malloc hooks
  common/macos-ports.cpp
  common/macos-ports.h
  runtime/allocator.cpp
  tests/cpp/runtime/_runtime-tests-env.cpp
  tests/cpp/runtime/allocator-malloc-replacement-test.cpp
Labels: refactoring

#657 added all changes and new features to documentation for Nov 2022
  README.md
  compiler/kphp2cpp.cpp
  docs/README.md
  docs/_config.yml
  docs/_includes/footer.liquid
  docs/assets/drawings/kphp-job-workers.drawio
  docs/assets/img/f1-f2-f3-g-t-r.png
  docs/assets/img/kphp-job-workers-feed-sort.drawio.png
  docs/assets/img/kphp-job-workers-manual.drawio.png
  docs/assets/img/kphp-job-workers-noreply.drawio.png
  docs/assets/img/kphp-job-workers-pieces-8.drawio.png
  docs/assets/img/kphp-job-workers-process.drawio.png
  docs/assets/img/kphp-job-workers-shared.drawio.png
  docs/assets/img/kphp-job-workers-simple.drawio.png
  docs/kphp-basics/compile-sample-script.md
  docs/kphp-basics/faq.md
  docs/kphp-basics/installation.md
  docs/kphp-basics/kphp-index-main-page.md
  docs/kphp-basics/quickstart-new-project.md
  docs/kphp-basics/roadmap.md
  docs/kphp-basics/typical-usage-issues.md
  docs/kphp-basics/whats-new.md
  docs/kphp-client/working-with-external-db/README.md
  docs/kphp-client/working-with-external-db/invoking-mysql.md
  docs/kphp-client/working-with-external-db/invoking-postgres-etc.md
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
  docs/kphp-internals/developing-and-extending-kphp/contributing-to-kphp.md
  docs/kphp-internals/kphp-architecture/internals-compiler.md
  docs/kphp-internals/kphp-architecture/internals-vkext.md
  docs/kphp-language/best-practices/async-programming-forks.md
  docs/kphp-language/best-practices/compiling-huge-projects.md
  docs/kphp-language/best-practices/embedded-profiler.md
  docs/kphp-language/best-practices/kphp-inspector-tool.md
  docs/kphp-language/best-practices/parallelism-job-workers.md
  docs/kphp-language/best-practices/performance-inspections.md
  docs/kphp-language/best-practices/shared-memory.md
  docs/kphp-language/howto-by-kphp/colored-functions.md
  docs/kphp-language/howto-by-kphp/compile-time-location.md
  docs/kphp-language/howto-by-kphp/exceptions.md
  docs/kphp-language/howto-by-kphp/json-encode-decode.md
  docs/kphp-language/howto-by-kphp/phpunit-mocks.md
  docs/kphp-language/howto-by-kphp/serialization-msgpack.md
  docs/kphp-language/howto-by-kphp/template-classes.md
  docs/kphp-language/howto-by-kphp/template-functions.md
  docs/kphp-language/kphp-vs-php/benchmarks.md
  docs/kphp-language/kphp-vs-php/compiler-cmd-options.md
  docs/kphp-language/kphp-vs-php/kphp-vs-php-differences.md
  docs/kphp-language/kphp-vs-php/list-of-additional-kphp-functions.md
  docs/kphp-language/kphp-vs-php/phpdoc-annotations.md
  docs/kphp-language/php-extensions/ffi.md
  docs/kphp-language/static-type-system/generic-classes.md
  docs/kphp-language/static-type-system/generic-functions.md
  docs/kphp-language/static-type-system/kphp-type-system.md
  docs/kphp-server/execution-options/server-cmd-options.md
  docs/kphp-server/kphp-as-backend/web-server.md
Labels: documentation

#667 [runtime] add the ability to specify json config to use inside the script
  builtin-functions/_functions.txt
  runtime/interface.cpp
  runtime/interface.h
  server/php-engine.cpp
  tests/python/tests/http_server/php/data/runtime_configuration.json
  tests/python/tests/http_server/php/index.php
  tests/python/tests/http_server/test_runtime_config.py
Labels: enhancement, runtime

#668 Fix unexpected memory piece error
  runtime/allocator.cpp
  runtime/allocator.h
  runtime/kphp-backtrace.cpp
  runtime/kphp-backtrace.h
  server/php-engine.cpp
  server/php-queries.cpp
  server/server-log.cpp
Labels: bug

#671 [runtime] fix sigsegv in init_runtime_environment
  runtime/interface.cpp
  server/php-runner.cpp
  server/php-worker.cpp
Labels: bug

#654 add ctype family of functions
  builtin-functions/_functions.txt
  runtime/ctype.cpp
  runtime/ctype.h
  runtime/interface.cpp
  runtime/interface.h
  runtime/runtime.cmake
  tests/python/lib/kphp_run_once.py
  tests/zend-test-list
Labels: missing functions

#685 [tests] install engines from deb packages for integration tests
  tests/kphp_ci_pipeline_runner.py
  tests/python/lib/file_utils.py
Labels: enhancement

#683 [vkext] Fix RPC TL `Maybe<array>` storing
  vkext/rpc-tests/main.php
  vkext/rpc-tests/memcache-rpc-tl-test.patch
  vkext/vkext-schema-memcache.cpp
  vkext/vkext.cpp
Labels: bug

#688 Add class name to job workers error messages
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/server-functions.cpp
  tests/python/tests/job_workers/test_job_errors.py
Labels: small fix
