Repository VKCOM/kphp, pull requests merged in 2022-10, with the labels that each got.

#630 Add virtual_builtin methods for builtin classes
  runtime/memcache.h
  runtime/tl/rpc_function.h
Labels: small fix

#633 [compiler] add a special case for int64_t min value codegen
  compiler/code-gen/vertex-compiler.cpp
  tests/phpt/phc/parsing/negative_literals.php
Labels: small fix

#636 don't perform allocations in php_warning if script allocator is disabled
  runtime/allocator.cpp
  runtime/allocator.h
  runtime/php_assert.cpp
Labels: bug

#607 fix memory leak in getopt()
  runtime/interface.cpp
Labels: bug

#616 [compiler] better type inference for switch cond var
  compiler/code-gen/vertex-compiler.cpp
  compiler/pipes/collect-main-edges.cpp
  compiler/vertex-desc.json
  compiler/vertex-meta_op_base.h
  tests/benchmarks/BenchmarkMultiSwitch.php
Labels: optimization

#604 fix preg_match() with wrong utf-8 offset
  builtin-functions/_functions.txt
  common/unicode/utf8-utils.h
  runtime/regexp.cpp
  runtime/regexp.h
  tests/phpt/regexp/008_preg_errors.php
Labels: bug

#637 [compiler] re-order class fields to reduce objects size
  compiler/code-gen/declarations.cpp
  compiler/code-gen/declarations.h
  tests/phpt/json/114_field_reorder.php
  tests/phpt/memory_usage/2_classes.php
  tests/phpt/msgpack_serialize/112_field_reorder.php
Labels: optimization

#640 [runtime] fix length handling in `string::to_int(char*, uint32_t)`
  runtime/string.inl
  tests/cpp/runtime/string-test.cpp
Labels: bug

#623 enable leak sanitizer
  common/sanitizer.h
  runtime/files.cpp
  server/php-runner.cpp
  server/php-runner.h
  server/php-worker.cpp
Labels: enhancement

#598 add DateTime class
  builtin-functions/_functions.txt
  runtime/datetime-class.cpp
  runtime/datetime-class.h
  runtime/datetime.cpp
  runtime/interface.cpp
  runtime/runtime.cmake
  runtime/timelib_wrapper.cpp
  runtime/timelib_wrapper.h
  tests/phpt/datetime/01_format.php
  tests/phpt/datetime/02_create.php
  tests/phpt/datetime/03_set_timestamp.php
  tests/phpt/datetime/04_modify.php
  tests/phpt/datetime/05_modify_wrong_modifier.php
  tests/phpt/datetime/06_set_date.php
  tests/phpt/datetime/07_set_time.php
  tests/phpt/datetime/08_date_time_zone.php
  tests/phpt/datetime/09_create_from_format.php
  tests/phpt/datetime/10_get_offset.php
Labels: missing functions

#642 fix non-backward compatibile name of master unix socket for graceful restart
  server/cluster-name.cpp
  tests/cpp/server/cluster-name-test.cpp
Labels: bug

#644 [tests] disable flaky integration test on ASAN
  tests/kphp_ci_pipeline_runner.py
Labels: small fix

#646 fix mysql implicit dependency
  runtime/pdo/mysql/mysql_pdo_emulated_statement.cpp
  runtime/pdo/mysql/mysql_pdo_emulated_statement.h
  runtime/pdo/pdo.cpp
  server/database-drivers/mysql/mysql.h
Labels: small fix

#647 [compiler] move some helper methods from GenTree to VertexUtil
  compiler/class-assumptions.cpp
  compiler/code-gen/declarations.cpp
  compiler/code-gen/raw-data.cpp
  compiler/code-gen/vertex-compiler.cpp
  compiler/compiler.cmake
  compiler/const-manipulations.h
  compiler/data/class-data.cpp
  compiler/gentree.cpp
  compiler/gentree.h
  compiler/inferring/expr-node.cpp
  compiler/inferring/ifi.cpp
  compiler/inferring/restriction-stacktrace-finder.cpp
  compiler/inferring/type-hint-recalc.cpp
  compiler/lambda-utils.cpp
  compiler/phpdoc.cpp
  compiler/pipes/analyze-performance.cpp
  compiler/pipes/cfg.cpp
  compiler/pipes/check-func-calls-and-vararg.cpp
  compiler/pipes/check-ub.cpp
  compiler/pipes/collect-const-vars.cpp
  compiler/pipes/collect-main-edges.cpp
  compiler/pipes/collect-required-and-classes.cpp
  compiler/pipes/convert-invoke-to-func-call.cpp
  compiler/pipes/convert-sprintf-calls.cpp
  compiler/pipes/deduce-implicit-types-and-casts.cpp
  compiler/pipes/extract-resumable-calls.cpp
  compiler/pipes/final-check.cpp
  compiler/pipes/gen-tree-postprocess.cpp
  compiler/pipes/generate-virtual-methods.cpp
  compiler/pipes/instantiate-ffi-operations.cpp
  compiler/pipes/instantiate-generics-and-lambdas.cpp
  compiler/pipes/optimization.cpp
  compiler/pipes/preprocess-exceptions.cpp
  compiler/pipes/register-ffi-scopes.cpp
  compiler/pipes/register-kphp-configuration.cpp
  compiler/pipes/register-variables.cpp
  compiler/pipes/resolve-self-static-parent.cpp
  compiler/pipes/split-switch.cpp
  compiler/vertex-util.cpp
  compiler/vertex-util.h
Labels: refactoring
