Repository VKCOM/kphp, pull requests merged in 2022-01, with the labels that each got.

#404 fix class instance can't be null issue
  compiler/inferring/restriction-isset.cpp
  tests/phpt/dl/1032_instance_can_be_null.php
  tests/phpt/dl/1033_string_cant_be_null.php
Labels: bug

#396 add support of array indexing inside const expression
  compiler/const-manipulations.h
  tests/phpt/dl/1010_const_vars.php
Labels: enhancement

#409 use kphp.readyV2 in tasks protocol if task worker mode is not default
  server/php-lease.cpp
Labels: small fix

#398 speed up tagger.cpp compilation
  compiler/code-gen/files/type-tagger.cpp
  compiler/code-gen/files/type-tagger.h
Labels: optimization

#403 refactored common and server stats
  common/kernel-version.cpp
  common/kprintf.cpp
  common/server/stats.cpp
  common/server/statsd-client.cpp
  common/server/tl-stats-t.h
  common/stats/provider.cpp
  common/stats/provider.h
  common/tl/parse.cpp
  common/version-string.cpp
  net/net-connections.cpp
  net/net-msg-buffers.cpp
  net/net-msg-buffers.h
  runtime/memory_resource/memory_resource.cpp
  server/confdata-stats.cpp
  server/confdata-stats.h
  server/job-workers/job-stats.cpp
  server/php-master.cpp
  server/server-stats.cpp
  server/statshouse/statshouse-client.cpp
Labels: refactoring

#408 refactor pch target for nocc support
  compiler/compiler-settings.cpp
  compiler/make/cpp-to-obj-target.h
  compiler/make/h-to-pch-target.h
  compiler/make/make.cpp
  compiler/make/target.h
Labels: refactoring

#402 use default linker for partial linking
  compiler/compiler-settings.cpp
  compiler/compiler-settings.h
  compiler/kphp2cpp.cpp
  compiler/make/objs-to-bin-target.h
  compiler/make/objs-to-obj-target.h
Labels: optimization

#390 forbid bad types in indexing
  compiler/pipes/final-check.cpp
  compiler/pipes/final-check.h
  tests/phpt/array/018_array_indexing_failire.php
  tests/phpt/array/019_array_indexing_ok.php
  tests/phpt/array/020_array_literal_failure.php
  tests/phpt/array/021_array_literal_ok.php
  tests/phpt/array/022_array_set_value_failure.php
  tests/phpt/array/023_array_set_value_ok.php
  tests/phpt/dl/1019_negative_string_offset.php
  tests/phpt/dl/467_rawid2long.php
  tests/phpt/null_coalescing/3_string.php
  tests/phpt/string_functions/005_string_indexing_failure.php
  tests/phpt/string_functions/006_string_indexing_ok.php
  tests/phpt/tup/110_tuple_indexing_failure.php
Labels: enhancement

#416 add to_array_debug() function
  builtin-functions/_functions.txt
  common/tl2php/gen-php-tests.cpp
  compiler/code-gen/declarations.cpp
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  compiler/pipes/final-check.cpp
  docs/kphp-basics/whats-new.md
  docs/kphp-internals/kphp-architecture/internals-runtime.md
  docs/kphp-language/best-practices/strict-typing-performance.md
  docs/kphp-language/howto-by-kphp/json-encode-decode.md
  docs/kphp-language/kphp-vs-php/list-of-additional-kphp-functions.md
  docs/kphp-language/static-type-system/instances.md
  docs/kphp-language/static-type-system/type-casting.md
  runtime/exception.h
  runtime/job-workers/job-interface.h
  runtime/tl/rpc_function.h
  runtime/to-array-processor.h
  tests/phpt/array/005_array_replace.php
  tests/phpt/array/010_array_swap_int_keys.php
  tests/phpt/cl/005_cast_to_array_debug.php
  tests/phpt/cl/006_interface_cast_to_array.php
  tests/phpt/cl/007_to_array_debug_with_extends.php
  tests/phpt/cl/008_fields_default_value.php
  tests/phpt/cl/009_to_array_debug_with_class_names.php
  tests/phpt/cl/116_wa_serialize.php
  tests/phpt/cl/140_class_from_fork.php
  tests/phpt/class_inheritance/010_to_array_debug.php
  tests/phpt/dl/1008_array_column.php
  tests/phpt/dl/1034_to_array_debug_shape.php
  tests/phpt/dl/1035_to_array_debug_tuple.php
  tests/phpt/ffi/004_to_array_debug_error.php
  tests/phpt/instance_cache/1_instance_cache.php
  tests/phpt/lambdas/016_typed_array_filter.php
  tests/phpt/lambdas/037_template_internal_functions_as_callbacks.php
  tests/phpt/lambdas/126_pass_array_of_ints_to_isntance_to_array.php
  tests/phpt/shapes/019_shape_to_array.php
  tests/python/tests/job_workers/php/SharedImmutableMessageScenario/http_worker.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/http_worker.php
Labels: enhancement
