Repository VKCOM/kphp, pull requests merged in 2022-09, with the labels that each got.

#603 fix ubsan alert in composer
  compiler/composer.cpp
Labels: bug

#608 fix NUMA availability checking
  server/numa-configuration.cpp
  server/php-engine.cpp
Labels: bug

#609 vkext 8.0
  vkext/rpc-tests/README.md
  vkext/rpc-tests/main.php
  vkext/rpc-tests/run-tests.py
  vkext/vk_zend.h
  vkext/vkext-json.cpp
  vkext/vkext-json.h
  vkext/vkext-rpc.cpp
  vkext/vkext-schema-memcache.cpp
  vkext/vkext-sp.cpp
  vkext/vkext-sp.h
  vkext/vkext-stats.cpp
  vkext/vkext-stats.h
  vkext/vkext-tl-memcache.cpp
  vkext/vkext.cmake
  vkext/vkext.cpp
  vkext/vkext.h
  vkext/vkext.stub.php
  vkext/vkext_arginfo.h
  vkext/vkext_legacy_arginfo.h
Labels: PHP8

#613 add strspn and strcspn functions
  builtin-functions/_functions.txt
  runtime/mixed.inl
  runtime/regexp.cpp
  runtime/string.inl
  runtime/string_decl.inl
  runtime/string_functions.cpp
  runtime/string_functions.h
  tests/phpt/string_functions/007_strspn.php
Labels: PHP7.4

#618 [runtime] fix string indexing (was broken during the refactoring)
  runtime/mixed.inl
  runtime/regexp.cpp
  runtime/string.inl
  runtime/string_decl.inl
  runtime/string_functions.cpp
Labels: bug

#619 fixed link to KPHPStorm plugin
  docs/_config.yml
Labels: documentation

#620 updated the documentation of the build for the mac
  docs/_config.yml
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
Labels: documentation

#612 Improve cluster name
  server/cluster-name.cpp
  server/cluster-name.h
  tests/cpp/server/cluster-name-test.cpp
Labels: small fix

#622 [runtime] optimize `strtolower` and `strtoupper`
  runtime/string_functions.cpp
  tests/phpt/string_functions/008_misc.php
Labels: runtime

#624 [runtime] fix strcasecmp behavior
  runtime/string_functions.cpp
  tests/phpt/string_functions/008_misc.php
Labels: bug

#628 [tests] improve python tests lib
  tests/python/lib/engine.py
  tests/python/lib/kphp_server.py
  tests/python/lib/tl_client.py
Labels: small fix

#629 Downgrade warning `Can't send job: not enough shared messages` to notice
  runtime/job-workers/client-functions.cpp
Labels: small fix
