Repository VKCOM/kphp, pull requests merged in 2022-06, with the labels that each got.

#526 [binlog] wait not existing binlog instead of error after LEV_ROTATE_TO processing
  common/binlog/binlog-buffer-aio.cpp
Labels: bug

#525 get rid of libmsgpack-dev dependency
  .github/workflows/Dockerfile.buster
  .github/workflows/Dockerfile.focal
  CMakeLists.txt
  compiler/code-gen/declarations.cpp
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
  runtime/msgpack-serialization.cpp
  runtime/msgpack-serialization.h
  runtime/msgpack/README.txt
  runtime/msgpack/adaptor_base.h
  runtime/msgpack/adaptors.h
  runtime/msgpack/check_instance_depth.cpp
  runtime/msgpack/check_instance_depth.h
  runtime/msgpack/object.h
  runtime/msgpack/object_visitor.cpp
  runtime/msgpack/object_visitor.h
  runtime/msgpack/packer.cpp
  runtime/msgpack/packer.h
  runtime/msgpack/parser.cpp
  runtime/msgpack/parser.h
  runtime/msgpack/sysdep.h
  runtime/msgpack/unpack_exception.h
  runtime/msgpack/unpacker.cpp
  runtime/msgpack/unpacker.h
  runtime/msgpack/zone.cpp
  runtime/msgpack/zone.h
  runtime/runtime.cmake
  runtime/string_buffer.inl
  runtime/string_buffer_decl.inl
Labels: enhancement, refactoring

#518 [runtime] make shutdown funcs called even after a timeout
  compiler/pipes/final-check.cpp
  runtime/interface.cpp
  runtime/interface.h
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  tests/phpt/shutdown_functions/throw_error1.php
  tests/phpt/shutdown_functions/throw_error2.php
  tests/phpt/shutdown_functions/throw_error3.php
  tests/python/tests/shutdown_functions/__init__.py
  tests/python/tests/shutdown_functions/php/index.php
  tests/python/tests/shutdown_functions/test_shutdown_functions.py
  tests/python/tests/shutdown_functions/test_shutdown_functions_errors.py
  tests/python/tests/shutdown_functions/test_shutdown_functions_exceptions.py
  tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py
Labels: enhancement, refactoring

#539 fixed info about current PHP language level support
  docs/kphp-language/kphp-vs-php/kphp-vs-php-differences.md
  docs/kphp-language/static-type-system/instances.md
  docs/kphp-language/static-type-system/kphp-type-system.md
  docs/kphp-language/static-type-system/phpdoc-to-declare-types.md
Labels: documentation
