Repository VKCOM/kphp, pull requests merged in 2022-08, with the labels that each got.

#567 [tests] change default server option to one worker
  tests/python/lib/kphp_server.py
  tests/python/tests/curl/test_curl.py
Labels: small fix

#561 Fix @kphp-flatten optimization for array<double>
  runtime/common_template_instantiations.cpp
  runtime/common_template_instantiations.h
Labels: small fix

#562 Refactor php worker and php script
  compiler/code-gen/files/init-scripts.cpp
  runtime/runtime.cmake
  server/database-drivers/adaptor.cpp
  server/database-drivers/adaptor.h
  server/job-workers/job-worker-server.cpp
  server/php-engine.cpp
  server/php-engine.h
  server/php-init-scripts.cpp
  server/php-init-scripts.h
  server/php-lease.cpp
  server/php-lease.h
  server/php-mc-connections.cpp
  server/php-mc-connections.h
  server/php-queries-types.cpp
  server/php-queries-types.h
  server/php-queries.cpp
  server/php-runner.cpp
  server/php-runner.h
  server/php-script.h
  server/php-sql-connections.cpp
  server/php-sql-connections.h
  server/php-worker.cpp
  server/php-worker.h
  server/server.cmake
Labels: refactoring

#558 [docs] describe JsonEncoder and all @kphp-json attributes
  docs/_includes/assets/custom.scss
  docs/assets/img/kphpstorm-json-1.png
  docs/assets/img/kphpstorm-json-2.png
  docs/assets/img/kphpstorm-json-3.png
  docs/assets/img/kphpstorm-json-4.png
  docs/kphp-internals/kphp-architecture/internals-runtime.md
  docs/kphp-language/best-practices/shared-memory.md
  docs/kphp-language/howto-by-kphp/json-encode-decode.md
Labels: documentation

#560 add function to send 103 http code
  builtin-functions/_functions.txt
  runtime/interface.cpp
  runtime/interface.h
  server/php-queries.cpp
  server/php-queries.h
  tests/python/lib/http_client.py
  tests/python/tests/http_server/php/index.php
  tests/python/tests/http_server/test_request.py
Labels: enhancement

#589 add php8 array_is_list function
  builtin-functions/_functions.txt
  runtime/array_functions.h
  tests/phpt/array/026_array_is_list.php
  tests/python/lib/file_utils.py
Labels: small fix, PHP8

#580 add more information about workers in logs
  server/json-logger.cpp
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-master.cpp
  tests/python/lib/kphp_server.py
Labels: small fix

#600 Add options for setting up coefficients for job workers communication limits
  server/job-workers/shared-memory-manager.cpp
  server/job-workers/shared-memory-manager.h
  server/php-engine.cpp
Labels: small fix

#575 add function ignore_user_abort
  builtin-functions/_functions.txt
  net/net-connections.cpp
  net/net-connections.h
  runtime/interface.cpp
  runtime/interface.h
  tests/python/lib/engine.py
  tests/python/lib/http_client.py
  tests/python/lib/kphp_server.py
  tests/python/lib/tl_client.py
  tests/python/tests/http_server/php/index.php
  tests/python/tests/http_server/test_ignore_user_abort.py
Labels: enhancement
