Repository VKCOM/kphp, pull requests merged in 2022-03, with the labels that each got.

#467 remove incorrect test
  tests/phpt/phc/codegen/016.php
Labels: small fix

#464 get rid of custom vk::constexpr_if() function
  common/type_traits/constexpr_if.h
  compiler/data/class-members.h
  compiler/gentree.cpp
  runtime/array_functions.h
  runtime/tl/tl_builtins.h
Labels: small fix

#444 implement array_unset() api function
  builtin-functions/_functions.txt
  runtime/array.inl
  runtime/array_decl.inl
  runtime/array_functions.h
  runtime/mixed.inl
  tests/phpt/array/024_array_unset.php
  tests/phpt/array/025_array_pop.php
Labels: enhancement

#460 avoid goto statement in autogenerated code for simple switch
  compiler/code-gen/vertex-compiler.cpp
Labels: enhancement

#466 add option for binding server to the specified IPv4 address
  common/kprintf.cpp
  net/net-socket.cpp
  net/net-socket.h
Labels: small fix

#473 Improved cpp17 support
  common/algorithms/adjacent_find.h
  common/algorithms/lower_bound.h
  common/algorithms/sort.h
  common/algorithms/stable_sort.h
  common/algorithms/upper_bound.h
  common/smart_iterators/transform_iterator.h
  common/tl/store.h
  common/wrappers/iterator_range.h
  runtime/array_functions.h
Labels: refactoring
