Repository VKCOM/kphp, pull requests merged in 2023-11, with the labels that each got.

#927 Install h3 from cmake
  .github/workflows/Build.yml
  cmake/external-libraries.cmake
  compiler/compiler-settings.cpp
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
Labels: enhancement, small fix

#923 Show version `kphp2cpp` in debug logs
  compiler/kphp2cpp.cpp
Labels: small fix, compiler

#929 fix initialization time metrics
  server/php-runner.cpp
Labels: small fix, runtime

#931 enable important signals in master initialization
  common/dl-utils-lite.cpp
  runtime/datetime/timelib_wrapper.cpp
  runtime/regexp.cpp
  server/php-engine.cpp
  tests/phpt/regexp/008_preg_errors.php
Labels: small fix, runtime

#926 maintained RpcReqError with headers in kphp
  runtime/rpc.cpp
  runtime/runtime.cmake
  runtime/tl/rpc_req_error.cpp
  runtime/tl/rpc_req_error.h
  runtime/tl/rpc_response.cpp
Labels: runtime

#897 Small unrelated improvements
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/php-runner.cpp
  server/php-worker.cpp
  server/server-stats.cpp
  server/server-stats.h
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
  tests/python/lib/kphp_run_once.py
  tests/python/lib/kphp_server.py
Labels: small fix, runtime

#932 Master-process initialization time stats
  server/php-engine.cpp
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: small fix, runtime

#934 fix regexp init heap memory usage
  runtime/datetime/timelib_wrapper.cpp
  runtime/regexp.cpp
  server/php-engine.cpp
  server/php-engine.h
  server/php-runner.cpp
  server/php-runner.h
Labels: runtime

#935 fix macos build
  common/dl-utils-lite.cpp
Labels: small fix

#936 Fix start/end time in measurement
  server/php-engine.cpp
Labels: bug
