Repository VKCOM/kphp, pull requests merged in 2023-06, with the labels that each got.

#841 enable shutdown functions on several timeout situations
  runtime/interface.cpp
  runtime/resumable.cpp
  runtime/runtime.cmake
  server/php-engine.cpp
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  server/server.cmake
  server/signal-handlers.cpp
  server/signal-handlers.h
  tests/python/tests/http_server/php/test_oom_handler.php
  tests/python/tests/http_server/test_oom_handler.py
  tests/python/tests/shutdown_functions/php/index.php
  tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py
Labels: runtime

#807 reset gzip flag
  runtime/interface.cpp
  tests/python/tests/http_server/php/index.php
  tests/python/tests/http_server/test_gzip_header_reset.py
Labels: small fix, runtime

#815 Allow trailing comma in tuples
  compiler/gentree.cpp
  tests/phpt/tup/001_tuple_create.php
  tests/phpt/tup/111_internal_comma.php
Labels: enhancement, small fix

#858 allow passing clang++-16 as a compiler in kphp_ci_pipeline_runner.py
  tests/kphp_ci_pipeline_runner.py
Labels: small fix

#840 move function bodies of auto generated classes in source files
  compiler/code-gen/declarations.cpp
  compiler/code-gen/declarations.h
  compiler/code-gen/includes.cpp
  compiler/code-gen/naming.h
  compiler/data/class-data.cpp
  compiler/data/class-data.h
  compiler/pipes/code-gen.cpp
Labels: enhancement, optimization

#859 Fixes in tracing binlog writer
  runtime/kphp_tracing.cpp
  runtime/kphp_tracing_binlog.h
  runtime/resumable.cpp
  runtime/resumable.h
Labels: small fix
