Repository VKCOM/kphp, pull requests merged in 2023-01, with the labels that each got.

#725 better handle functions that always throw/exit
  compiler/pipes/collect-main-edges.cpp
  tests/phpt/dl/1040_nohint_always_throw.php
  tests/phpt/exceptions/inheritance/29_throw_from_lambda3.php
  tests/phpt/phpdocs/030_hint_but_always_throw.php
Labels: bug

#713 fix a crash in OptimizationPass on indexing phpdoc leading to tp_Error
  compiler/pipes/final-check.cpp
  compiler/pipes/optimization.cpp
  tests/phpt/phc/parsing/impure.php
  tests/phpt/phpdocs/108_return_Unknown.php
  tests/phpt/phpdocs/109_param_Unknown.php
Labels: bug

#706 fix a race leading to 'invalid ()-invocation of a non-lambda'
  compiler/class-assumptions.cpp
  compiler/compiler.cpp
  compiler/pipes/convert-invoke-to-func-call.cpp
  compiler/pipes/convert-invoke-to-func-call.h
Labels: bug

#727 handle switch over a constexpr string, a pattern for generic factories
  compiler/code-gen/vertex-compiler.cpp
  compiler/gentree.cpp
  compiler/gentree.h
  compiler/pipes/generate-virtual-methods.cpp
  compiler/pipes/instantiate-generics-and-lambdas.cpp
  compiler/pipes/transform-to-smart-instanceof.cpp
  compiler/pipes/transform-to-smart-instanceof.h
  compiler/vertex-util.cpp
  compiler/vertex-util.h
  docs/kphp-language/static-type-system/generic-functions.md
  tests/phpt/generics/027_constexpr_switch.php
  tests/phpt/generics/028_constexpr_services_cont.php
  tests/phpt/generics/130_not_constexpr_switch_1.php
Labels: small fix

#731 Fix incorrect assert at RPC logging
  runtime/tl/rpc_tl_query.cpp
Labels: small fix

#729 fix modulite issue on inheriting Derived in modulite1 from Base in modulite2
  compiler/data/modulite-data.cpp
  compiler/data/modulite-data.h
  compiler/modulite-check-rules.cpp
  compiler/modulite-check-rules.h
  compiler/pipes/calc-real-defines-values.cpp
  compiler/pipes/inline-defines-usages.cpp
  tests/phpt/modulite/005_inheritance/005_inheritance.php
  tests/phpt/modulite/005_inheritance/ConnectNoMod005/ErrNoMod005.php
  tests/phpt/modulite/005_inheritance/SakCommon005/.modulite.yaml
  tests/phpt/modulite/005_inheritance/SakCommon005/ErrSak005.php
  tests/phpt/modulite/005_inheritance/plain005/.modulite.yaml
  tests/phpt/modulite/005_inheritance/plain005/plain005.php
Labels: bug

#726 support `new $class` and `$class::method()` for compile-time known strings
  builtin-functions/kphp_internal.txt
  compiler/class-assumptions.cpp
  compiler/compiler.cmake
  compiler/generics-reification.cpp
  compiler/gentree.cpp
  compiler/gentree.h
  compiler/phpdoc.cpp
  compiler/pipes/check-func-calls-and-vararg.cpp
  compiler/pipes/check-func-calls-and-vararg.h
  compiler/pipes/inline-defines-usages.cpp
  compiler/pipes/instantiate-generics-and-lambdas.cpp
  compiler/pipes/preprocess-exceptions.cpp
  compiler/rewrite-rules/replace-extern-func-calls.cpp
  compiler/rewrite-rules/replace-extern-func-calls.h
  compiler/type-hint.cpp
  compiler/type-hint.h
  compiler/vertex-util.cpp
  compiler/vertex-util.h
  docs/kphp-language/howto-by-kphp/call-function-by-name.md
  docs/kphp-language/static-type-system/generic-functions.md
  tests/kphp_tester.py
  tests/phpt/by_name/01_by_name_construct.php
  tests/phpt/by_name/02_by_name_call.php
  tests/phpt/by_name/03_by_name_get_const.php
  tests/phpt/by_name/04_by_name_get_field.php
  tests/phpt/by_name/100_by_name_non_constexpr.php
  tests/phpt/by_name/101_call_all_dynamic.php
  tests/phpt/by_name/102_get_unresolved.php
  tests/phpt/by_name/103_by_name_private_1.php
  tests/phpt/by_name/103_by_name_private_2.php
  tests/phpt/by_name/104_invalid_syntax_colons.php
  tests/phpt/by_name/105_direct_by_name_call.php
  tests/phpt/by_name/106_by_name_wrong_args.php
  tests/phpt/by_name/107_by_name_wrong_tinf.php
  tests/phpt/errors/006_method_params_n.php
  tests/phpt/errors/007_method_params_n_variadic.php
  tests/phpt/exceptions/18_set_location_error.php
  tests/phpt/ffi/typing/012_func_call_argcount_error.php
  tests/phpt/ffi/typing/013_func_call_argcount_error2.php
  tests/phpt/generics/129_bad_variadic_1.php
  tests/phpt/json/115_wrong_json_args_count.php
  tests/phpt/variadic_args/112_bad_count_after_unpack.php
Labels: enhancement
