Repository VKCOM/kphp, pull requests merged in 2023-10, with the labels that each got.

#911 StatsHouse metrics improvements
  builtin-functions/_functions.txt
  builtin-functions/kphp_toggles.txt
  runtime/interface.h
  server/php-engine.cpp
  server/php-master.cpp
  server/server-stats.cpp
  server/server-stats.h
  server/server.cmake
  server/shared-data-worker-cache.cpp
  server/shared-data-worker-cache.h
  server/shared-data.h
  server/statshouse/statshouse-client.cpp
  server/statshouse/statshouse-client.h
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: enhancement, runtime

#913 [tlo-parsing] Fix typo in tlo schema parser
  common/tlo-parsing/tlo-parser.cpp
Labels: bug

#891 add extra script time stats
  common/dl-utils-lite.cpp
  common/dl-utils-lite.h
  net/net-connections.cpp
  net/net-connections.h
  server/php-engine.cpp
  server/php-runner.cpp
  server/php-runner.h
  server/php-worker.cpp
  server/server-stats.cpp
  server/server-stats.h
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: enhancement

#899 add json log for timeout in net
  common/fast-backtrace.cpp
  common/fast-backtrace.h
  server/json-logger.cpp
  server/json-logger.h
  server/signal-handlers.cpp
Labels: small fix, runtime

#914 [tl-compiler] fix TLS_NAT_CONST magic
  common/tl/compiler/tl-tl.h
Labels: small fix

#920 TLS_NAT_CONST typo fixes
  common/tl/compiler/tl-parser-new.cpp
  vkext/vkext-rpc-tl-serialization.cpp
Labels: small fix
