Repository VKCOM/kphp, pull requests merged in 2023-07, with the labels that each got.

#860 add demangled stacktrace in exception logs
  runtime/php_assert.cpp
  runtime/runtime.cmake
Labels: small fix

#855 expose errors on `kphp_job_worker_store_response()`
  builtin-functions/_functions.txt
  runtime/job-workers/job-interface.h
  runtime/job-workers/server-functions.cpp
  runtime/job-workers/server-functions.h
Labels: small fix

#863 Fix clang16 build
  common/type_traits/is_copyable.h
  server/job-workers/pipe-io.h
Labels: small fix

#866 add more logs for 'resumable is already waited' warning
  runtime/resumable.cpp
Labels: runtime

#850 reset script state before run shutdown functions
  server/php-runner.cpp
  tests/python/tests/shutdown_functions/php/index.php
  tests/python/tests/shutdown_functions/test_shutdown_functions_timeouts.py
Labels: bug, runtime

#870 fix `curl_exec_concurrently` return type
  builtin-functions/_functions.txt
Labels: small fix

#865 server logs refactoring
  net/net-aes-keys.cpp
  net/net-aes-keys.h
  net/net-connections.cpp
  net/net-connections.h
  net/net-crypto-aes.cpp
  net/net-dc.cpp
  net/net-events.h
  net/net-http-server.cpp
  net/net-ifnet.cpp
  net/net-memcache-client.cpp
  net/net-memcache-server.cpp
  net/net-mysql-client.cpp
  net/net-reactor.cpp
  net/net-socket-options.cpp
  net/net-socket.cpp
  net/net-tcp-connections.cpp
  net/net-tcp-rpc-client.cpp
  net/net-tcp-rpc-common.cpp
  net/net-tcp-rpc-server.cpp
  runtime/curl.cpp
  runtime/resumable.cpp
  server/php-engine.cpp
  server/php-master.cpp
  server/php-master.h
  server/php-mc-connections.cpp
  server/php-queries-types.cpp
  server/php-queries.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/php-runner.h
  server/php-sql-connections.cpp
  server/php-worker.cpp
Labels: refactoring, runtime

#875 Small logs enrichment
  runtime/rpc.cpp
  runtime/rpc.h
  server/confdata-binlog-replay.cpp
Labels: small fix
