Repository VKCOM/kphp, pull requests merged in 2023-12, with the labels that each got.

#945 Moving options -Wall before extra_cxx_flags to resolve conflicting -Wno-XXX options for clang
  compiler/compiler-settings.cpp
Labels: small fix

#946 Make master outlive confdata out of shared memory errors
  runtime/array_decl.inl
  runtime/confdata-global-manager.cpp
  runtime/confdata-global-manager.h
  runtime/confdata-keys.cpp
  runtime/confdata-keys.h
  server/confdata-binlog-events.h
  server/confdata-binlog-replay.cpp
  server/confdata-binlog-replay.h
  server/confdata-stats.cpp
  server/confdata-stats.h
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
  server/signal-handlers.cpp
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
  tests/cpp/runtime/confdata-functions-test.cpp
  tests/python/lib/engine.py
  tests/python/lib/file_utils.py
  tests/python/tests/json_logs/test_signals.py
Labels: enhancement, runtime

#953 updated mysql-apt-config version for buster docker image
  .github/workflows/Dockerfile.buster
Labels: small fix

#940 refactor script backtrace for json logger
  common/fast-backtrace.cpp
  common/fast-backtrace.h
  server/json-logger.cpp
Labels: small fix, runtime
