Repository VKCOM/kphp, pull requests merged in 2024-02, with the labels that each got.

#960 fix sigsegv in JobWorkers on master graceful restart
  server/php-engine.cpp
Labels: small fix

#959 fix getdate sigsegv on overflow
  runtime/datetime/datetime_functions.cpp
Labels: small fix

#939 add support of polymorphic types in instance cache
  compiler/data/class-data.h
  compiler/pipes/final-check.cpp
  runtime/instance-cache.h
  tests/phpt/instance_cache/10_instance_cache_abstract_error.php
  tests/phpt/instance_cache/11_instance_cache_polymprphic_field.php
  tests/phpt/instance_cache/12_instance_cache_polymprphic_field_error.php
  tests/phpt/instance_cache/5_instance_cache_interface_error.php
  tests/phpt/instance_cache/5_instance_cache_polymorphic_simple.php
  tests/phpt/instance_cache/6_instance_cache_interface_field_error.php
  tests/phpt/instance_cache/6_instance_cache_polymorphic_error.php
  tests/phpt/instance_cache/7_instance_cache_interface.php
  tests/phpt/instance_cache/8_instance_cache_interface_error.php
  tests/phpt/instance_cache/9_instance_cache_abstract.php
  tests/phpt/interfaces/112_prohibit_instance_cache_mutable_interfaces.php
  tests/python/tests/instance_cache/php/index.php
  tests/python/tests/instance_cache/php/polymorphic_classes.php
  tests/python/tests/instance_cache/test_polymorphic.py
Labels: enhancement, runtime

#966 Add toggle to disable confdata soft OOM degradation mode
  server/confdata-binlog-replay.cpp
  server/confdata-binlog-replay.h
  server/php-engine.cpp
Labels: small fix

#938 prohibition of parallel rpc requests
  common/rpc-error-codes.h
  server/php-engine.cpp
Labels: small fix, runtime

#968 Fix issue with get_global_vars_memory_stats()
  runtime/kphp_tracing.h
Labels: small fix

#942 fixed cyclic traversal of classes to measure memory consumption
  compiler/code-gen/declarations.cpp
  runtime/dummy-visitor-methods.h
  runtime/exception.h
  runtime/ffi.h
  runtime/job-workers/job-interface.cpp
  runtime/job-workers/job-interface.h
  runtime/memcache.h
  runtime/memory_usage.cpp
  runtime/memory_usage.h
  runtime/mysql.h
  runtime/runtime.cmake
  runtime/tl/rpc_function.h
  tests/phpt/memory_usage/11_shapes.php
  tests/phpt/memory_usage/2_classes.php
Labels: bug, refactoring
