Repository VKCOM/kphp, pull requests merged in 2024-11, with the labels that each got.

#1133 Update K2 header to version 8
  runtime-light/header.h
Labels: runtime, k2

#1135 Fix installation in CMakeLists
  CMakeLists.txt
Labels: bug, small fix

#1132 Move some KPHP tracing functionality into runtime-common/stdlib
  runtime-common/stdlib/tracing/tracing-context.h
  runtime-common/stdlib/tracing/tracing-functions.h
  runtime-common/stdlib/tracing/tracing.h
  runtime/curl.cpp
  runtime/exec.cpp
  runtime/files.cpp
  runtime/interface.cpp
  runtime/job-workers/client-functions.cpp
  runtime/job-workers/processing-jobs.cpp
  runtime/kphp_tracing.cpp
  runtime/kphp_tracing.h
  runtime/php_assert.cpp
  runtime/regexp.cpp
  runtime/regexp.h
  runtime/resumable.cpp
  runtime/rpc.cpp
  runtime/typed_rpc.cpp
  server/php-runner.cpp
  tests/phpt/tracing/change_level.php
Labels: runtime, k2

#1138 K2: use special refcnt for shared globals
  compiler/pipes/final-check.cpp
  runtime-common/stdlib/string/string-context.h
  runtime-light/component/image.h
  runtime-light/tl/tl-builtins.cpp
  runtime/string-context.cpp
Labels: k2

#1140 K2: refactor to use std::string_view instead of string literals
  runtime-common/stdlib/string/string-context.h
  runtime-light/core/globals/php-script-globals.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/init-functions.h
  runtime-light/server/job-worker/init-functions.h
  runtime-light/state/component-state.cpp
  runtime-light/state/component-state.h
  runtime-light/state/instance-state.cpp
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime/datetime/datetime_functions.cpp
Labels: refactoring, k2

#1142 K2: implement ini_get
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/unsupported-functions.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  runtime-light/state/component-state.cpp
  runtime-light/state/component-state.h
  runtime-light/stdlib/server/args-functions.h
Labels: k2

#1122 Get rid of CMAKE_INSTALL_PREFIX in some places
  cmake/init-global-vars.cmake
  vkext/vkext.cmake
Labels: bug

#1147 revert "Improve code layout in runtime (#1112)"
  runtime-common/core/core-types/decl/mixed_decl.inl
  runtime-common/core/core-types/decl/string_decl.inl
  runtime-common/core/core-types/definition/mixed.cpp
  runtime-common/core/core-types/definition/mixed.inl
  runtime-common/core/core-types/definition/string.cpp
  runtime-common/core/core-types/definition/string.inl
Labels: small fix

#1127 add efficient user context manipulation routines
  CMakeLists.txt
  common/common-tests.cmake
  common/common.cmake
  common/dl-utils-lite.cpp
  common/dl-utils-lite.h
  common/server/crash-dump.cpp
  common/ucontext/darwin/aarch64/context.cpp
  common/ucontext/darwin/aarch64/context.h
  common/ucontext/darwin/x86_64/context.h
  common/ucontext/linux/aarch64/context.h
  common/ucontext/linux/x86_64/context.h
  common/ucontext/linux/x86_64/defs.h
  common/ucontext/linux/x86_64/getcontext.S
  common/ucontext/linux/x86_64/makecontext.cpp
  common/ucontext/linux/x86_64/setcontext.S
  common/ucontext/linux/x86_64/startcontext.S
  common/ucontext/linux/x86_64/swapcontext.S
  common/ucontext/ucontext-arm.h
  common/ucontext/ucontext-portable-test.cpp
  common/ucontext/ucontext-portable.h
  server/json-logger.cpp
  server/php-queries.cpp
  server/php-runner.cpp
  server/php-runner.h
  server/signal-handlers.cpp
  server/signal-handlers.h
Labels: enhancement, optimization, runtime

#1146 Added some logs about PHP streams processing
  runtime/streams.cpp
Labels: runtime

#1143 Added ready job workers count metric
  .idea/misc.xml
  server/statshouse/statshouse-manager.cpp
Labels: small fix, runtime

#1148 Added new confdata statshouse metrics
  server/confdata-stats.cpp
  server/confdata-stats.h
  server/statshouse/statshouse-manager.cpp
Labels: runtime

#1151 remove error-prone dumper of aarch64 registers
  common/server/crash-dump.cpp
Labels: bug

#1149 K2: implement basename function
  builtin-functions/kphp-light/file.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/unsupported-functions.txt
  runtime-common/stdlib/math/math-functions.cpp
  runtime-common/stdlib/math/math-functions.h
  runtime-common/stdlib/stdlib.cmake
  runtime-light/stdlib/file/file-system-functions.h
  tests/phpt/filesystem/basename.php
Labels: k2

#1153 Add GitHub Linguist rules
  .gitattributes
Labels: enhancement

#1156 remove some of debug symbols
  compiler/code-gen/code-generator.cpp
  compiler/compiler-core.h
  compiler/pipes/register-kphp-configuration.cpp
  compiler/pipes/register-kphp-configuration.h
Labels: compiler

#1145 Move some url functions into runtime-common
  builtin-functions/kphp-light/hash.txt
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/string.txt
  runtime-common/stdlib/server/url-functions.cpp
  runtime-common/stdlib/server/url-functions.h
  runtime-common/stdlib/stdlib.cmake
  runtime-light/server/http/init-functions.cpp
  runtime-light/stdlib/hash/hash-functions.cpp
  runtime-light/stdlib/stdlib.cmake
  runtime-light/tl/tl-types.h
  runtime/interface.cpp
  runtime/url.cpp
  runtime/url.h
  tests/phpt/dl/432_rawurlencode.php
Labels: runtime, k2

#1155 K2: implement gzcompress and gzuncompress
  builtin-functions/kphp-light/hash.txt
  cmake/init-global-vars.cmake
  compiler/make/objs-to-k2-component-target.h
  compiler/runtime_link_libs.h.in
  runtime-light/allocator/runtime-light-allocator.cpp
  runtime-light/runtime-light.cmake
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/zlib/zlib-functions.cpp
  runtime-light/stdlib/zlib/zlib-functions.h
  runtime/runtime.cmake
  tests/kphp_ci_pipeline_runner.py
  tests/phpt/pk/017_gzip.php
  third-party/zlib-cmake/zlib.cmake
Labels: k2

#1150 add time functions
  builtin-functions/kphp-light/crypto.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/kphp_internal.txt
  builtin-functions/kphp-light/time.txt
  builtin-functions/kphp-light/unsupported-functions.txt
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/time/time-functions.cpp
  runtime-light/stdlib/time/time-functions.h
  tests/phpt/func_specializations/hrtime.php
  tests/phpt/func_specializations/hrtime_error1.php
  tests/phpt/func_specializations/hrtime_error2.php
  tests/phpt/func_specializations/microtime.php
  tests/phpt/func_specializations/microtime_error1.php
  tests/phpt/func_specializations/microtime_error2.php
  tests/phpt/pk/005_date.php
Labels: runtime, k2

#1159 K2: start using abseil-cpp
  runtime-light/runtime-light.cmake
  runtime-light/server/http/init-functions.cpp
  runtime-light/stdlib/zlib/zlib-functions.cpp
  third-party/abseil-cpp-cmake/abseil-cpp.cmake
  third-party/zlib-cmake/zlib.cmake
Labels: k2

#1162 Support new PMC snapshot header
  common/binlog/binlog-snapshot.h
  server/confdata-binlog-replay.cpp
Labels: runtime

#1160 [k2] crypto cbc ciphers
  builtin-functions/kphp-light/crypto.txt
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.h
  runtime-light/stdlib/crypto/crypto_schema.tl
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.h
  tests/phpt/openssl/11_openssl_decrypt.php
Labels: k2

#1163 disable debug info for asm files
  common/common.cmake
Labels: small fix, runtime

#1167 K2: implement md5 function
  builtin-functions/kphp-light/crypto.txt
  builtin-functions/kphp-light/hash.txt
  cmake/popular-common.cmake
  common/md5.cpp
  common/md5.h
  runtime-light/stdlib/crypto/crypto-functions.h
  tests/phpt/optimizations/010_str_concat.php
  tests/phpt/optimizations/011_md5concat.php
Labels: k2
