Repository VKCOM/kphp, pull requests merged in 2024-12, with the labels that each got.

#1171 Move some array functions into runtime-common
  builtin-functions/kphp-light/array.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/kphp_internal.txt
  builtin-functions/kphp-light/math.txt
  builtin-functions/kphp-light/unsupported-functions.txt
  builtin-functions/kphp-light/unsupported/arrays.txt
  runtime-common/stdlib/array/array-functions.cpp
  runtime-common/stdlib/array/array-functions.h
  runtime-common/stdlib/math/random-functions.h
  runtime-common/stdlib/stdlib.cmake
  runtime-light/state/instance-state.h
  runtime-light/stdlib/array/array-functions.h
  runtime-light/stdlib/math/random-functions.h
  runtime-light/stdlib/math/random-state.cpp
  runtime-light/stdlib/math/random-state.h
  runtime-light/stdlib/stdlib.cmake
  runtime/array_functions.cpp
  runtime/array_functions.h
  runtime/math_functions.cpp
  runtime/math_functions.h
  tests/phpt/array/011_array_reserve_vector.php
  tests/phpt/array/012_array_reserve_map_int_keys.php
  tests/phpt/array/013_array_reserve_map_string_keys.php
  tests/phpt/array/017_array_unique.php
  tests/phpt/array/024_array_unset.php
  tests/phpt/array/025_array_pop.php
  tests/phpt/array/026_implode.php
  tests/phpt/array/030_explode_error.php
  tests/phpt/cl/133_array_merge_instances.php
  tests/phpt/dl/1011_cast_const_array_init_value.php
  tests/phpt/dl/1012_array_key_exists.php
  tests/phpt/dl/1022_change_order_for_assignment_to_list.php
  tests/phpt/dl/387_mt_rand.php
  tests/phpt/dl/452_isset.php
  tests/phpt/dl/492_array_map.php
  tests/phpt/dl/504_array_keys_as.php
  tests/phpt/dl/968_valist.php
  tests/phpt/generics/018_classof_keyword.php
  tests/phpt/pk/010_array_search.php
  tests/phpt/variadic_args/016_unpack_positional.php
Labels: runtime, k2

#1172 [k2] fix vkcom compilation with runtime light
  builtin-functions/kphp-light/hash.txt
  builtin-functions/kphp-light/regex.txt
  builtin-functions/kphp-light/time.txt
  runtime-common/stdlib/array/array-functions.h
  runtime-light/stdlib/string/regex-functions.h
  runtime-light/stdlib/time/time-functions.cpp
  runtime-light/stdlib/time/time-functions.h
  runtime-light/stdlib/zlib/zlib-functions.h
  runtime/array_functions.h
  tests/phpt/performance_inspections/8_array_reserve_no_warn.php
Labels: small fix, k2

#1174 [k2] implement simple HTTP server
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  compiler/make/objs-to-k2-component-target.h
  runtime-common/core/memory-resource/resource_allocator.h
  runtime-common/stdlib/server/url-functions.cpp
  runtime-common/stdlib/server/url-functions.h
  runtime-light/core/globals/php-script-globals.h
  runtime-light/runtime-light.cmake
  runtime-light/server/http/http-server-state.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/server/init-functions.h
  runtime-light/state/init-functions.cpp
  runtime-light/state/init-functions.h
  runtime-light/state/instance-state.cpp
  runtime-light/state/instance-state.h
  runtime-light/stdlib/server/http-functions.cpp
  runtime-light/stdlib/server/http-functions.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/zlib/zlib-functions.cpp
  runtime-light/tl/tl-types.h
  runtime/url.cpp
  runtime/url.h
  third-party/abseil-cpp-cmake/abseil-cpp.cmake
Labels: k2

#1116 Support ArrayAccess
  builtin-functions/kphp-full/_functions.txt
  builtin-functions/kphp-light/functions.txt
  compiler/code-gen/vertex-compiler.cpp
  compiler/compiler.cmake
  compiler/compiler.cpp
  compiler/data/class-data.h
  compiler/gentree.cpp
  compiler/inferring/expr-node.h
  compiler/inferring/primitive-type.h
  compiler/inferring/type-data.cpp
  compiler/inferring/type-data.h
  compiler/pipes/array-access-transform.cpp
  compiler/pipes/array-access-transform.h
  compiler/pipes/calc-bad-vars.cpp
  compiler/pipes/calc-func-dep.cpp
  compiler/pipes/check-ub.cpp
  compiler/pipes/filter-only-actually-used.cpp
  compiler/pipes/final-check.cpp
  compiler/pipes/inline-simple-functions.cpp
  compiler/pipes/inline-simple-functions.h
  compiler/pipes/optimization.cpp
  compiler/pipes/optimization.h
  compiler/pipes/preprocess-eq3.cpp
  compiler/vertex-desc.json
  runtime-common/core/array_access.h
  runtime-common/core/class-instance/class-instance-decl.inl
  runtime-common/core/core-types/decl/mixed_decl.inl
  runtime-common/core/core-types/definition/mixed.cpp
  runtime-common/core/core-types/definition/mixed.inl
  runtime-common/core/runtime-core.h
  tests/cpp/runtime/_runtime-tests-env.cpp
  tests/phpt/array_access/001_set_and_get_by_index.php
  tests/phpt/array_access/002_set_append.php
  tests/phpt/array_access/003_as_array_access.php
  tests/phpt/array_access/004_with_instanceof.php
  tests/phpt/array_access/005_inheritance.php
  tests/phpt/array_access/006_as_mixed.php
  tests/phpt/array_access/007_assignment_chain.php
  tests/phpt/array_access/008_isset_unset.php
  tests/phpt/array_access/009_empty.php
  tests/phpt/array_access/010_multi_dim.php
  tests/phpt/array_access/011_in_arr.php
  tests/phpt/array_access/012_fun_and_field.php
  tests/phpt/array_access/013_with_callable.php
  tests/phpt/array_access/100_not_implement.php
  tests/phpt/array_access/101_not_override.php
  tests/phpt/array_access/102_as_mixed_non_aa.php
  tests/phpt/array_access/Classes/KeysableArrayAccess.php
  tests/phpt/array_access/Classes/LikeArray.php
  tests/phpt/array_access/Classes/LoggingLikeArray.php
  tests/phpt/array_access/Classes/User.php
Labels: enhancement, missing functionality, compiler

#1178 Fix `mixed::operator[]` usage in runtime-light
  runtime-light/stdlib/string/regex-functions.cpp
Labels: bug, k2

#1179 Fix bug with traversal of directories during reading KML models
  runtime/kphp_ml/kphp_ml_init.cpp
Labels: bug, small fix, runtime

#1177 [k2] implement register_shutdown_function
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  compiler/compiler-settings.cpp
  runtime-common/core/memory-resource/resource_allocator.h
  runtime-light/runtime-light.cmake
  runtime-light/runtime-light.cpp
  runtime-light/state/instance-state.cpp
  runtime-light/state/instance-state.h
  runtime-light/stdlib/exit/exit-functions.cpp
  runtime-light/stdlib/exit/exit-functions.h
  runtime-light/stdlib/server/handler-functions.h
  runtime-light/stdlib/string/regex-include.h
  runtime-light/stdlib/system/system-functions.h
  runtime-light/utils/concepts.h
  tests/phpt/dl/403_shutdown.php
  tests/phpt/shutdown_functions/no_leak_in_lambda.php
  third-party/pcre2-cmake/pcre2.cmake
Labels: k2

#1180 Move serialize & unserialize builtins to runtime-common
  builtin-functions/kphp-light/math.txt
  builtin-functions/kphp-light/serialize.txt
  runtime-common/stdlib/serialization/serialize-functions.cpp
  runtime-common/stdlib/serialization/serialize-functions.h
  runtime-common/stdlib/stdlib.cmake
  runtime-light/stdlib/math/random-functions.h
  runtime/memcache.cpp
  runtime/runtime.cmake
  tests/phpt/dl/444_serialize.php
  tests/phpt/dl/490_serialize.php
Labels: runtime, k2

#1176 move array functions into common
  builtin-functions/kphp-light/array.txt
  builtin-functions/kphp-light/unsupported/arrays.txt
  runtime-common/stdlib/array/array-functions.cpp
  runtime-common/stdlib/array/array-functions.h
  runtime-light/stdlib/array/array-functions.h
  runtime/array_functions.cpp
  runtime/array_functions.h
  tests/phpt/array/003_array_flip.php
  tests/phpt/array/004.array_merge_into.php
  tests/phpt/array/005_array_replace.php
  tests/phpt/array/006_array_sum.php
  tests/phpt/array/014_array_rand.php
  tests/phpt/array/015_array_replace_neg_keys.php
  tests/phpt/array/019_array_indexing_ok.php
Labels: k2

#1181 Move hexdec & dechex builtins to runtime-common
  builtin-functions/kphp-light/math.txt
  builtin-functions/kphp-light/unsupported/misc.txt
  runtime-common/stdlib/math/math-functions.cpp
  runtime-common/stdlib/math/math-functions.h
  runtime-common/stdlib/stdlib.cmake
  runtime/math_functions.cpp
  runtime/math_functions.h
  tests/phpt/dl/435_base64_encode.php
  tests/phpt/dl/455_inc_xor_str.php
  tests/phpt/dl/488_ipv6.php
  tests/phpt/dl/489_hexdec.php
Labels: runtime, k2

#1183 Temporary OOM functional tests disabling
  tests/python/tests/http_server/test_oom_handler.py
Labels: small fix, runtime

#1184 [k2] implement php_uname & posix_getpid
  builtin-functions/kphp-light/file.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/system.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
  runtime-light/state/image-state.h
  runtime-light/stdlib/system/system-functions.h
Labels: k2

#1186 [k2] implement setcookie & setrawcookie
  builtin-functions/kphp-light/server.txt
  runtime-light/server/http/http-server-state.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/stdlib/server/http-functions.cpp
  runtime-light/stdlib/server/http-functions.h
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.h
Labels: k2

#1161 [k2] add file functions in runtime light
  builtin-functions/kphp-light/file.txt
  runtime-light/coroutine/awaitable.h
  runtime-light/k2-platform/k2-api.h
  runtime-light/scheduler/scheduler.cpp
  runtime-light/state/init-functions.cpp
  runtime-light/state/instance-state.cpp
  runtime-light/state/instance-state.h
  runtime-light/stdlib/component/component-api.cpp
  runtime-light/stdlib/component/component-api.h
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime-light/stdlib/file/file-stream-functions.h
  runtime-light/stdlib/file/file-system-functions.cpp
  runtime-light/stdlib/file/file-system-functions.h
  runtime-light/stdlib/file/file-system-state.cpp
  runtime-light/stdlib/file/file-system-state.h
  runtime-light/stdlib/file/resource.cpp
  runtime-light/stdlib/file/resource.h
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/stdlib/stdlib.cmake
Labels: runtime, k2

#1187 [k2] add http body compression
  runtime-light/server/http/http-server-state.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/stdlib/zlib/zlib-functions.cpp
  runtime-light/stdlib/zlib/zlib-functions.h
Labels: k2

#1188 [k2] add default arguments to rpc send builtins
  builtin-functions/kphp-light/rpc.txt
Labels: k2

#1189 [k2] enable php8 migration warning builtin
  builtin-functions/kphp-light/kphp-toggles.txt
Labels: k2

#1191 [k2] support environment variables
  compiler/code-gen/vertex-compiler.cpp
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
  runtime-light/state/component-state.cpp
  runtime-light/state/component-state.h
  runtime-light/state/instance-state.cpp
  runtime-light/stdlib/string/regex-functions.cpp
Labels: k2

#1192 Move preg_quote to runtime-common
  builtin-functions/kphp-light/regex.txt
  runtime-common/stdlib/stdlib.cmake
  runtime-common/stdlib/string/regex-functions.cpp
  runtime-common/stdlib/string/regex-functions.h
  runtime-light/stdlib/string/regex-functions.cpp
  runtime-light/stdlib/string/regex-functions.h
  runtime/regexp.cpp
  runtime/regexp.h
  tests/phpt/regexp/006_preg_quote.php
Labels: runtime, k2

#1194 temporary rename regex-functions.cpp in runtime-common
  runtime-common/stdlib/stdlib.cmake
  runtime-common/stdlib/string/regex-functions-common.cpp
Labels: bug

#1201 prevent false-positive `stack-buffer-overflow` ASan detections on signal stack
  server/php-runner.cpp
  tests/python/tests/http_server/test_oom_handler.py
Labels: bug, runtime
