Repository VKCOM/kphp, pull requests merged in 2024-10, with the labels that each got.

#1111 add `kphp_request_script_time_max_running_interval` mertric collecting
  server/php-runner.cpp
  server/php-runner.h
  server/server-stats.cpp
  server/server-stats.h
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: runtime

#1113 Fix GitHub actions
  .github/workflows/Build.yml
  .github/workflows/Dockerfile.buster
  .github/workflows/Dockerfile.focal
  .github/workflows/Dockerfile.jammy
  .github/workflows/macos.yml
Labels: small fix

#1112 Improve code layout in runtime
  runtime-core/core-types/decl/mixed_decl.inl
  runtime-core/core-types/decl/string_decl.inl
  runtime-core/core-types/definition/mixed.cpp
  runtime-core/core-types/definition/mixed.inl
  runtime-core/core-types/definition/string.cpp
  runtime-core/core-types/definition/string.inl
Labels: optimization

#1114 Skip some tests in K2 mode
  tests/phpt/dl/1008_fail_class_instance_with_index_key.php
  tests/phpt/string_functions/010_xor_strings.php
  tests/phpt/string_functions/011_str_getcsv.php
Labels: k2

#1107 Add support for JSON serialized confdata values
  runtime/memcache.cpp
  runtime/memcache.h
Labels: enhancement, runtime

#1110 K2: add confdata related builtins
  builtin-functions/kphp-light/confdata.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/unsupported/server.txt
  runtime-light/component/component.cpp
  runtime-light/component/component.h
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime-light/stdlib/confdata/confdata-functions.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
  tests/k2-components/test_confdata.php
Labels: runtime, k2

#1118 K2: add State to start_fork_t, wait_fork_t, and wait_with_timeout_t
  runtime-light/coroutine/awaitable.h
Labels: runtime, k2

#1115 Add new StatsHouse metrics
  server/php-queries.h
  server/php-runner.cpp
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: runtime

#1079 add more by host metrics
  server/statshouse/statshouse-manager.cpp
Labels: small fix

#1119 remove global php_disable_warnings
  runtime/interface.cpp
  runtime/php_assert.cpp
  runtime/php_assert.h
  tests/cpp/runtime/_runtime-tests-env.cpp
  tests/phpt/warnings/6_disable_warnings.php
Labels: bug

#1123 Use python3.13 for macos CI
  .github/workflows/Build.yml
  .github/workflows/macos.yml
Labels: small fix

#1117 K2: add new CI steps
  tests/kphp_ci_pipeline_runner.py
  tests/phpt/pk/030_header_register_callback_unreachable_in_cli.php
  tests/phpt/pk/031_header_register_callback_no_invoked_by_flush.php
  tests/python/lib/kphp_run_once.py
Labels: enhancement, k2

#1121 K2: add TL types and functions for HTTP queries
  runtime-light/component/init-functions.cpp
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/tl/tl-core.cpp
  runtime-light/tl/tl-core.h
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
Labels: runtime, k2

#1124 Initial support for K2 http queries
  runtime-light/component/component.cpp
  runtime-light/component/component.h
  runtime-light/component/init-functions.cpp
  runtime-light/core/globals/php-script-globals.h
  runtime-light/runtime-light.cmake
  runtime-light/server/http/http-server-context.cpp
  runtime-light/server/http/http-server-context.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/server/init-functions.h
  runtime-light/server/job-worker/init-functions.h
  runtime-light/server/job-worker/job-worker-server-context.cpp
  runtime-light/server/job-worker/job-worker-server-context.h
  runtime-light/server/server.cmake
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/stdlib/job-worker/job-worker-client-context.cpp
  runtime-light/stdlib/job-worker/job-worker-client-context.h
  runtime-light/stdlib/stdlib.cmake
Labels: runtime, k2

#1120 compile unsupported vkcom
  builtin-functions/kphp-light/crypto.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/job-workers.txt
  builtin-functions/kphp-light/rpc.txt
  builtin-functions/kphp-light/unsupported-functions.txt
  builtin-functions/kphp-light/unsupported/curl.txt
  builtin-functions/kphp-light/unsupported/error.txt
  builtin-functions/kphp-light/unsupported/file.txt
  builtin-functions/kphp-light/unsupported/fork.txt
  builtin-functions/kphp-light/unsupported/kphp-toggles.txt
  builtin-functions/kphp-light/unsupported/kphp-tracing.txt
  builtin-functions/kphp-light/unsupported/math.txt
  builtin-functions/kphp-light/unsupported/misc.txt
  builtin-functions/kphp-light/unsupported/regex.txt
  builtin-functions/kphp-light/unsupported/rpc.txt
  builtin-functions/kphp-light/unsupported/string.txt
  builtin-functions/kphp-light/unsupported/time.txt
  compiler/code-gen/declarations.cpp
  compiler/code-gen/files/tl2cpp/tl2cpp.cpp
  compiler/code-gen/files/tracing-autogen.cpp
  compiler/code-gen/vertex-compiler.cpp
  runtime-light/component/component.h
  runtime-light/runtime-light.cmake
  runtime-light/stdlib/array/array-functions.h
  runtime-light/stdlib/crypto/crypto-context.cpp
  runtime-light/stdlib/crypto/crypto-context.h
  runtime-light/stdlib/crypto/crypto-functions.h
  runtime-light/stdlib/fork/fork-functions.h
  runtime-light/stdlib/hash/hash-functions.h
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/stdlib/job-worker/job-worker-api.h
  runtime-light/stdlib/math/math.h
  runtime-light/stdlib/regex/regex-functions.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/string/string-functions.h
  runtime-light/stdlib/system/system-context.cpp
  runtime-light/stdlib/system/system-context.h
  runtime-light/stdlib/system/system-functions.h
  runtime-light/stdlib/tracing/tracing-functions.h
  runtime-light/utils/null_coalesce.h
  runtime-light/utils/to-array-processor.h
  runtime/null_coalesce.h
  tests/k2-components/test_job_worker.php
  tests/k2-components/test_job_worker_multi.php
  tests/k2-components/test_job_worker_noreply.php
  tests/k2-components/test_rpc_memcached.php
Labels: runtime, compiler, k2

#1128 K2: add wrappers for libc allocator functions
  compiler/code-gen/files/shape-keys.cpp
  compiler/make/objs-to-k2-component-target.h
  runtime-light/allocator/allocator.cmake
  runtime-light/allocator/libc-alloc-wrapper.cpp
Labels: runtime, k2
