Repository VKCOM/kphp, pull requests merged in 2025-03, with the labels that each got.

#1227 solve few issues in runtime-light
  builtin-functions/kphp-light/error.txt
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/kphp-toggles.txt
  builtin-functions/kphp-light/rpc.txt
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/string.txt
  builtin-functions/kphp-light/system.txt
  builtin-functions/kphp-light/unsupported/fork.txt
  builtin-functions/kphp-light/unsupported/kml.txt
  builtin-functions/kphp-light/unsupported/kphp-tracing.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  runtime-common/stdlib/array/array-functions.h
  runtime-light/core/globals/php-script-globals.h
  runtime-light/stdlib/array/array-functions.h
  runtime-light/stdlib/file/file-system-functions.h
  runtime-light/stdlib/fork/fork-functions.h
  runtime-light/stdlib/instance-cache/instance-cache.h
  runtime-light/stdlib/job-worker/job-worker.h
  runtime-light/stdlib/output/http-functions.h
  runtime-light/stdlib/output/output-buffer.cpp
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/serialization/json-functions.h
  runtime-light/stdlib/server/handler-functions.h
  runtime-light/stdlib/server/http-functions.h
  runtime-light/stdlib/system/system-functions.h
  runtime-light/stdlib/tracing/tracing-functions.h
  runtime/array_functions.h
Labels: runtime, k2

#1246 move some array functions into runtime-common
  builtin-functions/kphp-light/array.txt
  builtin-functions/kphp-light/unsupported/arrays.txt
  runtime-common/stdlib/array/array-functions.h
  runtime-light/stdlib/array/array-functions.h
  runtime/array_functions.h
  tests/phpt/dl/1016_array_first_key.php
Labels: runtime, k2

#1248 Fix array assignment type mismatch
  compiler/inferring/var-node.cpp
  tests/phpt/array/033_insert_same_type_error.php
  tests/phpt/array/034_insert_more_dim_type_error.php
Labels: bug, compiler

#1247 [k2] fix async builtin lambda's return type
  builtin-functions/kphp-light/array.txt
  builtin-functions/kphp-light/unsupported/arrays.txt
  compiler/code-gen/vertex-compiler.cpp
  runtime-light/stdlib/array/array-functions.h
  tests/phpt/array/009_array_filter_by_key.php
  tests/phpt/lambdas/016_typed_array_filter.php
  tests/phpt/lambdas/017_typed_array_map.php
Labels: bug, k2

#1231 [k2] switch to c++23
  cmake/init-compilation-flags.cmake
  compiler/compiler-settings.cpp
  compiler/make/make.cpp
  runtime-light/coroutine/task.h
  runtime-light/tl/tl-types.h
  runtime-light/utils/panic.cpp
  runtime-light/utils/php_assert.cpp
Labels: k2

#1249 added `hostname` output to json logs
  server/json-logger.cpp
  server/json-logger.h
  server/php-engine.cpp
  tests/python/tests/json_logs/test_exceptions.py
  tests/python/tests/json_logs/test_signals.py
  tests/python/tests/json_logs/test_timeouts.py
  tests/python/tests/json_logs/test_warnings.py
Labels: enhancement, runtime

#1240 use murmur hash for class name hashing
  builtin-functions/kphp-light/functions.txt
  cmake/popular-common.cmake
  common/common.cmake
  compiler/compiler.cmake
  compiler/data/class-data.h
  runtime-light/stdlib/component/component-api.h
  runtime-light/stdlib/job-worker/job-worker.h
  runtime-light/stdlib/rpc/rpc-extra-info.cpp
  runtime-light/stdlib/rpc/rpc-extra-info.h
  runtime-light/stdlib/rpc/rpc-tl-function.h
  runtime/datetime/date_interval.h
  runtime/datetime/datetime.h
  runtime/datetime/datetime_immutable.h
  runtime/datetime/datetime_interface.h
  runtime/datetime/datetime_zone.h
  runtime/exception.h
  runtime/ffi.h
  runtime/job-workers/job-interface.h
  runtime/memcache.h
  runtime/pdo/pdo.h
  runtime/pdo/pdo_statement.h
  runtime/rpc.h
  runtime/rpc_extra_info.h
  runtime/spl/array_iterator.h
  runtime/tl/rpc_function.h
  server/confdata-binlog-events.h
Labels: runtime, k2

#1253 force libkphp-full-runtime recombining when runtime is modified
  cmake/utils.cmake
Labels: small fix

#1256 [k2] add full runtime archive as a build artifact
  CMakeLists.txt
  compiler/compiler-settings.cpp
  compiler/make/make.cpp
  compiler/make/objs-to-k2-component-target.h
  compiler/runtime_compile_flags.h.in
  compiler/runtime_link_flags.h.in
  compiler/runtime_link_libs.h.in
  runtime-light/runtime-light.cmake
  third-party/pcre2-cmake/pcre2.cmake
  third-party/re2-cmake/re2.cmake
Labels: k2

#1257 [k2] small fixes
  runtime-light/stdlib/job-worker/job-worker.h
  runtime-light/stdlib/rpc/rpc-tl-function.h
  third-party/pcre2-cmake/pcre2.cmake
Labels: k2

#1258 [k2] update cmake install directives
  CMakeLists.txt
Labels: k2

#1259 Add --statsd-prefix option
  common/server/statsd-client.cpp
  common/server/statsd-client.h
Labels: small fix, runtime

#1262 [k2] add php_sapi_name
  builtin-functions/kphp-light/stdlib/system-functions.txt
  runtime-light/core/globals/php-script-globals.h
  runtime-light/state/instance-state.cpp
  runtime-light/stdlib/system/system-functions.h
  tests/phpt/lambdas/026_pass_string_into_callable_argument.php
Labels: k2

#1266 make re2c is not required for whole project
  cmake/init-global-vars.cmake
  third-party/timelib-cmake/timelib.cmake
Labels: small fix, runtime

#1267 [k2] fix codegen for null coalescing operator
  builtin-functions/kphp-light/stdlib/error.txt
  compiler/code-gen/code-generator.h
  compiler/code-gen/vertex-compiler.cpp
  tests/phpt/null_coalescing/8_throw_exceptions.php
Labels: bug, k2

#1268 [k2] do not use third-party archives with force-link runtime
  compiler/make/objs-to-k2-component-target.h
Labels: k2

#1271 update KPHP documentation
  .github/workflows/Dockerfile.docs
  .github/workflows/docs-site.yml
  docs/Dockerfile
  docs/_config.yml
  docs/_includes/footer.liquid
  docs/kphp-internals/developing-and-extending-kphp/compiling-kphp-from-sources.md
Labels: documentation, CI/CD

#1263 [k2] add misc builtins
  builtin-functions/kphp-light/stdlib/array-functions.txt
  builtin-functions/kphp-light/stdlib/file-functions.txt
  builtin-functions/kphp-light/stdlib/kphp-tracing.txt
  builtin-functions/kphp-light/stdlib/server-functions.txt
  builtin-functions/kphp-light/stdlib/system-functions.txt
  runtime-light/stdlib/instance-cache/instance-cache.h
  runtime-light/stdlib/output/print-functions.h
  runtime-light/stdlib/system/system-functions.h
  runtime-light/stdlib/tracing/tracing-functions.h
Labels: k2

#1264 Implementation of stderr in K2
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
  runtime-light/stdlib/file/resource.cpp
  runtime-light/stdlib/file/resource.h
Labels: k2

#1265 move malloc interface to common
  runtime-common/core/allocator/script-malloc-interface.h
  runtime-common/stdlib/msgpack/zone.cpp
  runtime-light/state/init-functions.cpp
  runtime-light/stdlib/component/component-api.cpp
  runtime-light/stdlib/string/regex-state.cpp
  runtime-light/streams/streams.cpp
  runtime-light/streams/streams.h
  runtime/allocator.cpp
  runtime/allocator.h
Labels: runtime, k2
