Repository VKCOM/kphp, pull requests merged in 2025-09, with the labels that each got.

#1396 [k2] add partial files support
  builtin-functions/kphp-light/stdlib/file-functions.txt
  runtime-light/k2-platform/k2-api.h
  runtime-light/server/cli/init-functions.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/server/rpc/init-functions.cpp
  runtime-light/server/rpc/init-functions.h
  runtime-light/state/instance-state.cpp
  runtime-light/stdlib/component/component-api.h
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/diagnostics/exception-types.h
  runtime-light/stdlib/file/file-system-functions.h
  runtime-light/stdlib/file/resource.cpp
  runtime-light/stdlib/file/resource.h
  runtime-light/stdlib/instance-cache/instance-cache-functions.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/stdlib.cmake
  runtime-light/streams/read-ext.h
  runtime-light/streams/stream.h
Labels: k2

#1401 [k2] support runtime-config argument
  runtime-light/state/component-state.cpp
  runtime-light/state/component-state.h
  tests/python/lib/k2_server.py
  tests/python/tests/http_server/php/data/component-config.yaml
Labels: k2

#1409 explicitly specifies version `cmake` `3.31.6` for `macos`
  .github/workflows/macos.yml
Labels: CI/CD

#1384 removed query parameters for curl metrics
  server/statshouse/statshouse-manager.cpp
Labels: small fix
