Repository VKCOM/kphp, pull requests merged in 2025-04, with the labels that each got.

#1274 Better fopen() logs
  runtime-light/stdlib/file/file-system-functions.cpp
Labels: small fix, k2

#1273 [k2] coroutines refactoring
  compiler/code-gen/declarations.cpp
  compiler/code-gen/files/init-scripts.cpp
  compiler/code-gen/vertex-compiler.cpp
  runtime-common/stdlib/string/string-context.h
  runtime-light/core/globals/php-init-scripts.h
  runtime-light/coroutine/awaitable.h
  runtime-light/coroutine/shared-task.h
  runtime-light/coroutine/task.h
  runtime-light/coroutine/type-traits.h
  runtime-light/scheduler/scheduler.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/state/component-state.h
  runtime-light/state/init-functions.cpp
  runtime-light/state/init-functions.h
  runtime-light/state/instance-state.cpp
  runtime-light/state/instance-state.h
  runtime-light/stdlib/array/array-functions.h
  runtime-light/stdlib/component/component-api.cpp
  runtime-light/stdlib/component/component-api.h
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime-light/stdlib/confdata/confdata-functions.h
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.h
  runtime-light/stdlib/exit/exit-functions.cpp
  runtime-light/stdlib/exit/exit-functions.h
  runtime-light/stdlib/file/file-system-functions.cpp
  runtime-light/stdlib/file/file-system-functions.h
  runtime-light/stdlib/file/resource.h
  runtime-light/stdlib/fork/fork-functions.h
  runtime-light/stdlib/fork/fork-state.h
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/stdlib/job-worker/job-worker-api.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/server/handler-functions.h
  runtime-light/stdlib/string/regex-functions.h
  runtime-light/stdlib/system/system-functions.h
  runtime-light/stdlib/time/timer-functions.h
  runtime-light/streams/streams.cpp
  runtime-light/streams/streams.h
  runtime-light/utils/null_coalesce.h
Labels: k2

#1275 [k2] change kphp::rpc::VALID_QUERY_ID_RANGE_START from 0 to 1
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/rpc/rpc-state.h
Labels: k2

#1279 [k2] get rid of locale dependent functions in http contexts
  .github/workflows/Build.yml
  .github/workflows/macos.yml
  runtime-light/server/http/http-server-state.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/stdlib/server/http-functions.cpp
Labels: k2

#1278 fixed the build for clang version 17
  cmake/init-compilation-flags.cmake
  runtime/signal_safe_hashtable.h
  server/server-stats.cpp
Labels: refactoring

#1282 add .git-blame-ignore-revs file
  .git-blame-ignore-revs
Labels: refactoring

#1283 add CI pipeline to check code style
  .github/workflows/pr-code-format.yml
Labels: CI/CD

#1280 fix order of worker's cleanup operations
  runtime/interface.cpp
  tests/python/tests/shutdown_functions/php/index.php
  tests/python/tests/shutdown_functions/test_shutdown_functions_capture_shared_mem.py
Labels: bug, runtime

#1261 added datacenter name to statistics
  server/server-config.cpp
  server/server-config.h
  server/statshouse/statshouse-client.cpp
  server/statshouse/statshouse-client.h
  server/statshouse/statshouse-manager.cpp
Labels: enhancement, runtime

#1286 fix dependecy graph of build
  server/server.cmake
Labels: small fix, runtime

#1287 [k2] refactor rpc client
  runtime-light/stdlib/fork/fork-functions.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/rpc/rpc-extra-headers.cpp
  runtime-light/stdlib/rpc/rpc-extra-headers.h
  runtime-light/stdlib/rpc/rpc-extra-info.cpp
  runtime-light/stdlib/rpc/rpc-extra-info.h
  runtime-light/stdlib/rpc/rpc-state.h
  runtime-light/stdlib/rpc/rpc-tl-builtins.cpp
  runtime-light/stdlib/rpc/rpc-tl-builtins.h
  runtime-light/stdlib/rpc/rpc-tl-error.cpp
  runtime-light/stdlib/stdlib.cmake
  runtime-light/tl/tl-core.h
  runtime-light/tl/tl.cmake
Labels: refactoring, k2

#857 merging CI scripts between master and branches
  .github/workflows/Build.yml
  .github/workflows/debian.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  README.md
Labels: refactoring, CI/CD

#1289 fix incorrect reference to OpenSSL headers
  common/binlog/binlog.cmake
  common/common.cmake
  compiler/compiler.cmake
  net/net.cmake
  server/server.cmake
Labels: small fix, runtime

#1291 [k2] make allocator wrapper a distinct library
  runtime-light/allocator-wrapper/allocator-wrapper.cmake
  runtime-light/allocator-wrapper/libc-alloc-wrapper.cpp
  runtime-light/allocator/allocator.cmake
  runtime-light/runtime-light.cmake
Labels: k2

#1288 [k2] add exception handling to RPC functions
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/server/init-functions.h
  runtime-light/server/job-worker/init-functions.h
  runtime-light/state/init-functions.cpp
  runtime-light/stdlib/diagnostics/exception-functions.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/rpc/rpc-exceptions.h
  runtime-light/stdlib/rpc/rpc-tl-builtins.cpp
  runtime-light/stdlib/rpc/rpc-tl-builtins.h
  runtime-light/stdlib/rpc/rpc-tl-error.cpp
  runtime-light/stdlib/rpc/rpc-tl-error.h
  runtime-light/stdlib/rpc/rpc-tl-query.cpp
  runtime-light/stdlib/rpc/rpc-tl-query.h
  runtime-light/stdlib/server/http-functions.cpp
Labels: k2

#1296 [k2] enhance TL library
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/job-worker/init-functions.h
  runtime-light/state/init-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/tl/tl-core.h
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
Labels: k2

#1293 Get rid of C++ exceptions in msgpack
  common/wrappers/string_view.h
  compiler/code-gen/declarations.cpp
  runtime-common/stdlib/msgpack/adaptors.h
  runtime-common/stdlib/msgpack/object.h
  runtime-common/stdlib/msgpack/object_visitor.cpp
  runtime-common/stdlib/msgpack/object_visitor.h
  runtime-common/stdlib/msgpack/unpack_exception.h
  runtime-common/stdlib/msgpack/unpacker.cpp
  runtime-common/stdlib/msgpack/unpacker.h
  runtime-common/stdlib/msgpack/zone.cpp
  runtime-common/stdlib/serialization/msgpack-functions.h
  runtime-common/stdlib/serialization/serialization-context.h
  runtime-light/stdlib/serialization/msgpack-functions.h
  runtime/msgpack-serialization.h
  tests/cpp/runtime/msgpack-test.cpp
  tests/phpt/msgpack_serialize/029_deserialize_bad_then_good.php
Labels: runtime

#1298 fix k2 python tests
  tests/kphp_ci_pipeline_runner.py
Labels: CI/CD

#1297 [k2] add rpc server: part1
  runtime-light/server/init-functions.h
  runtime-light/server/job-worker/job-worker-server-state.h
  runtime-light/server/rpc/init-functions.cpp
  runtime-light/server/rpc/init-functions.h
  runtime-light/server/rpc/rpc-server-state.cpp
  runtime-light/server/rpc/rpc-server-state.h
  runtime-light/server/server.cmake
  runtime-light/state/image-state.h
  runtime-light/state/init-functions.cpp
  runtime-light/state/instance-state.h
  runtime-light/stdlib/crypto/crypto-state.h
  runtime-light/stdlib/curl/curl-state.h
  runtime-light/stdlib/diagnostics/exception-functions.h
  runtime-light/stdlib/file/file-system-state.h
  runtime-light/stdlib/job-worker/job-worker-client-state.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/rpc/rpc-client-state.cpp
  runtime-light/stdlib/rpc/rpc-client-state.h
  runtime-light/stdlib/rpc/rpc-extra-info.cpp
  runtime-light/stdlib/rpc/rpc-tl-builtins.cpp
  runtime-light/stdlib/rpc/rpc-tl-builtins.h
  runtime-light/stdlib/rpc/rpc-tl-kphp-request.h
  runtime-light/stdlib/rpc/rpc-tl-query.cpp
  runtime-light/stdlib/rpc/rpc-tl-query.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/system/system-state.h
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
Labels: k2

#1300 force disable mysql fixture for k2 tests
  tests/python/tests/sql_client/test_mysql.py
Labels: CI/CD

#1301 [k2] rpc server: part2
  builtin-functions/kphp-light/stdlib/rpc.txt
  compiler/code-gen/files/init-scripts.cpp
  compiler/code-gen/files/tl2cpp/tl2cpp.cpp
  runtime-light/server/init-functions.h
  runtime-light/server/rpc/init-functions.cpp
  runtime-light/server/rpc/rpc-server-state.h
  runtime-light/state/init-functions.cpp
  runtime-light/state/init-functions.h
  runtime-light/state/instance-state.cpp
  runtime-light/state/instance-state.h
  runtime-light/state/state.cmake
  runtime-light/stdlib/file/resource.cpp
  runtime-light/stdlib/job-worker/job-worker-api.h
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/rpc/rpc-client-state.h
  runtime-light/stdlib/rpc/rpc-constants.h
  runtime-light/stdlib/rpc/rpc-tl-query.cpp
  runtime-light/tl/tl-core.h
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
Labels: k2

#1302 [k2] fix http server prologue
  runtime-light/state/instance-state.cpp
Labels: bug, k2
