Repository VKCOM/kphp, pull requests merged in 2025-07, with the labels that each got.

#1359 [k2] use script allocator instead of k2::alloc for coroutine frames
  runtime-light/allocator/runtime-light-allocator.cpp
  runtime-light/coroutine/shared-task.h
  runtime-light/coroutine/task.h
Labels: k2

#1363 Add kml_available_models()
  builtin-functions/kphp-full/kml.txt
  runtime/kphp_ml/kphp_ml_init.h
  runtime/kphp_ml/kphp_ml_interface.cpp
  runtime/kphp_ml/kphp_ml_interface.h
  tests/python/tests/kml/catboost/php/unrelated_to_inference.php
Labels: compiler

#1365 [k2] update k2-header
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
  runtime-light/utils/logs.h
Labels: k2

#1361 [k2] add trace as tag in log
  runtime-light/stdlib/diagnostics/backtrace.h
  runtime-light/utils/logs.h
  tests/python/lib/file_utils.py
  tests/python/lib/k2_server.py
  tests/python/lib/web_server.py
  tests/python/tests/conftest.py
  tests/python/tests/json_logs/test_warnings.py
Labels: k2

#1366 move base_convert to runtime-common
  builtin-functions/kphp-light/stdlib/string-functions.txt
  runtime-common/stdlib/math/math-functions.cpp
  runtime-common/stdlib/math/math-functions.h
  runtime/math_functions.cpp
  runtime/math_functions.h
  tests/phpt/dl/486_base_convert.php
Labels: runtime, k2

#1362 [k2] adapt array functions
  builtin-functions/kphp-light/stdlib/array-functions.txt
  runtime-common/stdlib/array/array-functions.h
  runtime-light/stdlib/array/array-functions.h
  runtime/array_functions.h
  tests/phpt/array/001_array_combine.php
  tests/phpt/array/002_array_fill_keys.php
  tests/phpt/array/008_array_find.php
  tests/phpt/array/010_array_swap_int_keys.php
  tests/phpt/array/016_array_merge_recursive.php
  tests/phpt/array/035_get_key_by_pos.php
  tests/phpt/array/036_get_value_by_pos.php
  tests/phpt/dl/1003_array_pad.php
  tests/phpt/dl/1006_array_diff_assoc.php
  tests/phpt/dl/1007_array_intersect_assoc.php
  tests/phpt/dl/1008_array_column.php
  tests/phpt/dl/993_benchmark_primes.php
  tests/phpt/dl/999_misc_001.php
  tests/phpt/lambdas/125_callback_with_complicated_type_rule.php
Labels: k2

#1374 Fix dynamic incremental linkage in k2 mode
  compiler/compiler-settings.cpp
Labels: bug, k2

#1369 add virtual builtins stats
  runtime/interface.cpp
  runtime/openssl.cpp
  runtime/runtime-builtin-stats.h
  runtime/streams.cpp
  server/server-stats.cpp
  server/server-stats.h
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: runtime

#742 updated links in documentation
  docs/_config.yml
  docs/kphp-internals/kphp-architecture/internals-vkext.md
  docs/kphp-language/best-practices/embedded-profiler.md
  docs/kphp-language/kphp-vs-php/list-of-additional-kphp-functions.md
  docs/kphp-language/php-extensions/ffi.md
Labels: documentation
