Repository VKCOM/kphp, pull requests merged in 2025-08, with the labels that each got.

#1377 add kphp_slow_curl_response metric
  runtime/curl.cpp
  server/php-queries.h
  server/php-runner.cpp
  server/statshouse/statshouse-manager.cpp
Labels: runtime

#1382 [k2] refactor the io_scheduler a bit
  runtime-light/coroutine/detail/poll-info.h
  runtime-light/coroutine/io-scheduler.h
Labels: refactoring, k2

#1385 Add k2-lib mode
  compiler/code-gen/const-globals-batched-mem.cpp
  compiler/code-gen/files/const-vars-init.cpp
  compiler/code-gen/files/init-scripts.cpp
  compiler/compiler-core.cpp
  compiler/compiler-core.h
  compiler/compiler-settings.cpp
  compiler/kphp2cpp.cpp
  compiler/make/make.cpp
  compiler/pipes/calc-bad-vars.cpp
  compiler/pipes/calc-empty-functions.cpp
  compiler/pipes/code-gen.cpp
  compiler/pipes/gen-tree-postprocess.cpp
  compiler/pipes/remove-empty-function-calls.cpp
  tests/python/lib/testcase.py
  tests/python/tests/libs/test_libs.py
Labels: enhancement, compiler, k2

#1387 Implement `getrandmax()` and `srand()` for runtime light
  builtin-functions/kphp-light/stdlib/math-functions.txt
  runtime-common/stdlib/math/random-functions.h
  runtime-light/stdlib/math/random-functions.h
  runtime/math_functions.cpp
  runtime/math_functions.h
Labels: k2

#1390 [k2] add interruptible tag in k2-lib functions.txt
  compiler/code-gen/files/lib-header.cpp
Labels: small fix, compiler, k2

#1386 [k2] implement user-defined tags in logs
  builtin-functions/kphp-light/stdlib/error.txt
  runtime-light/state/instance-state.h
  runtime-light/stdlib/diagnostics/contextual-logger.cpp
  runtime-light/stdlib/diagnostics/contextual-logger.h
  runtime-light/stdlib/diagnostics/detail/logs.h
  runtime-light/stdlib/diagnostics/logs.cpp
  runtime-light/stdlib/diagnostics/logs.h
  runtime-light/stdlib/diagnostics/raw-logger.h
  runtime-light/stdlib/server/http-functions.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/system/system-functions.h
  tests/python/lib/k2_server.py
  tests/python/lib/web_server.py
  tests/python/tests/json_logs/test_warnings.py
Labels: k2

#1392 [k2] update k2-header
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
Labels: k2

#1394 [k2] update k2-header to 12 version
  runtime-light/k2-platform/k2-header.h
Labels: k2

#1395 [k2] implement filesize and realpath
  builtin-functions/kphp-light/stdlib/file-functions.txt
  runtime-light/k2-platform/k2-api.h
  runtime-light/stdlib/file/file-system-functions.h
  tests/phpt/pk/004_OrFalse.php
Labels: k2

#1393 [k2] Add some tracing, wait queue stubs and remove some rpc ones
  builtin-functions/kphp-light/stdlib/kphp-tracing.txt
  builtin-functions/kphp-light/stdlib/rpc.txt
  runtime-light/stdlib/fork/fork-functions.h
  runtime-light/stdlib/tracing/tracing-div.h
  runtime-light/stdlib/tracing/tracing-functions.h
  runtime-light/stdlib/tracing/tracing-span.h
Labels: k2
