Repository VKCOM/kphp, pull requests merged in 2025-06, with the labels that each got.

#1333 [k2] small enhancements in k2 header
  runtime-light/k2-platform/k2-api.h
Labels: k2

#1332 [k2] add backtrace_symbols
  runtime-light/k2-platform/k2-header.h
  runtime-light/stdlib/diagnostics/backtrace.h
  runtime-light/stdlib/diagnostics/error-handling-functions.h
  tests/python/lib/testcase.py
  tests/python/tests/diagnostic/php/data/component-config.yaml
  tests/python/tests/diagnostic/php/index.php
  tests/python/tests/diagnostic/test_backtrace.py
Labels: k2

#1339 [k2] fix async-stack for task coroutine
  runtime-light/coroutine/shared-task.h
  runtime-light/coroutine/task.h
Labels: k2

#1340 [k2] add sync backtrace
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
  runtime-light/stdlib/diagnostics/backtrace.cpp
  runtime-light/stdlib/diagnostics/backtrace.h
Labels: k2

#1343 Fix global vars refcnt
  compiler/pipes/optimization.cpp
Labels: bug, compiler

#1344 use optimized string ctor in http_build_query
  runtime-common/stdlib/server/url-functions.h
Labels: runtime

#1347 add runtime builtin stats
  builtin-functions/kphp-light/core/kphp_internal.txt
  builtin-functions/kphp-light/stdlib/file-functions.txt
  builtin-functions/kphp-light/stdlib/math-functions.txt
  builtin-functions/kphp-light/stdlib/system-functions.txt
  compiler/code-gen/vertex-compiler.cpp
  compiler/compiler-core.cpp
  compiler/compiler-core.h
  compiler/compiler-settings.h
  compiler/compiler.cpp
  compiler/kphp2cpp.cpp
  runtime-common/core/allocator/script-allocator.h
  runtime-common/core/runtime-core.h
  runtime/interface.cpp
  runtime/runtime-builtin-stats.h
  server/php-engine.cpp
  server/php-runner.cpp
  server/server-stats.cpp
  server/server-stats.h
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: runtime, compiler

#1349 Implement special pre-fork run once mode
  server/database-drivers/adaptor.h
  server/php-engine-vars.cpp
  server/php-engine-vars.h
  server/php-engine.cpp
Labels: enhancement, runtime

#1346 make confdata reader more reliable
  common/binlog/binlog-buffer-aio.cpp
  common/binlog/binlog-buffer-replay.cpp
  common/binlog/binlog-buffer.cpp
  common/binlog/binlog-buffer.h
  common/binlog/binlog-stats.h
  common/binlog/binlog.cmake
  common/common.cmake
  common/kfs/kfs.cpp
  common/server/engine-settings.h
  common/server/init-binlog.cpp
  server/confdata-binlog-replay.cpp
  server/confdata-binlog-replay.h
  server/php-engine.cpp
  server/statshouse/statshouse-manager.cpp
  server/statshouse/statshouse-manager.h
Labels: enhancement, runtime

#1319 http method to give metrics in `OpenMetrics` format
  cmake/init-compilation-flags.cmake
  common/server/open-metrics-stats-t.h
  common/server/stats.cpp
  common/server/stats.h
  common/server/statsd-client.cpp
  common/stats/provider.cpp
  common/stats/provider.h
  server/php-master.cpp
Labels: enhancement, runtime

#1353 Make file buckets count flexible
  compiler/compiler-settings.h
  compiler/kphp2cpp.cpp
  compiler/pipes/code-gen.cpp
Labels: bug, compiler
