Repository VKCOM/kphp, pull requests merged in 2025-05, with the labels that each got.

#1307 fix macos ci
  .github/workflows/macos.yml
Labels: CI/CD

#1306 updated the `clang-format` rules
  .clang-format
  common/wrappers/gnu-builtins.h
  common/wrappers/to_array.h
  runtime-light/memory-resource-impl/monotonic-light-buffer-resource.cpp
  runtime/critical_section.h
  runtime/memory_resource_impl/memory_resource_stats.cpp
  runtime/memory_resource_impl/monotonic_runtime_buffer_resource.cpp
  runtime/uber-h3.h
Labels: refactoring

#1308 disable gzip test in K2 mode
  tests/python/tests/http_server/test_gzip_header_reset.py
Labels: bug, CI/CD

#1290 Basic implementation of instance cache in k2
  builtin-functions/kphp-light/functions.txt
  builtin-functions/kphp-light/stdlib/instance-cache.txt
  builtin-functions/kphp-light/stdlib/server-functions.txt
  compiler/gentree.cpp
  compiler/pipes/final-check.cpp
  runtime-common/core/core-types/definition/mixed.inl
  runtime-light/state/instance-state.h
  runtime-light/stdlib/instance-cache/instance-cache-functions.h
  runtime-light/stdlib/instance-cache/instance-cache-state.cpp
  runtime-light/stdlib/instance-cache/instance-cache-state.h
  runtime-light/stdlib/instance-cache/instance-cache.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/tl/tl-functions.h
  tests/phpt/instance_cache/13_instance_cache_serializable.php
  tests/phpt/mixed/non_primitive/002_instanceof.php
  tests/python/lib/kphp_run_once.py
  tests/python/tests/http_server/php/A.php
  tests/python/tests/instance_cache_serialized/__init__.py
  tests/python/tests/instance_cache_serialized/php/data/component-config.yaml
  tests/python/tests/instance_cache_serialized/php/index.php
  tests/python/tests/instance_cache_serialized/test_store_fetch_delete.py
Labels: k2

#1304 fixed a bug with bool type mapping in vkext
  vkext/vkext-rpc-tl-serialization.cpp
Labels: bug

#1311 [k2] implement gzencode, gzdecode, gzdeflate, gzinflate
  builtin-functions/kphp-light/stdlib/zlib-functions.txt
  runtime-light/stdlib/zlib/zlib-functions.cpp
  runtime-light/stdlib/zlib/zlib-functions.h
Labels: k2

#1312 fixed the path to python tests in CI
  .github/workflows/debian.yml
  .github/workflows/ubuntu.yml
Labels: CI/CD

#1313 move http_build_query to runtime-common
  builtin-functions/kphp-light/stdlib/server-functions.txt
  runtime-common/stdlib/server/url-functions.h
  runtime-light/stdlib/server/http-functions.h
  runtime/openssl.cpp
  runtime/runtime.cmake
  runtime/url.cpp
  runtime/url.h
  tests/phpt/dl/481_parse_str_with_empty_string.php
  tests/phpt/pk/006_http_build.php
Labels: runtime, k2

#1314 Add upper check for `hard-memory-limit` option on start
  server/php-engine.cpp
Labels: small fix, runtime

#1317 updated the `macos` image to `15` and enabled running the build for `c++20`
  .github/workflows/macos.yml
  cmake/init-compilation-flags.cmake
Labels: CI/CD

#1303 [k2] add RPC server tests
  tests/python/lib/k2_server.py
  tests/python/tests/conftest.py
Labels: k2

#1310 [k2] rpc server part 3
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/server/rpc/init-functions.cpp
  runtime-light/server/rpc/init-functions.h
  runtime-light/state/instance-state.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
Labels: k2

#1322 [k2] add integration tests step to kphp_ci_pipeline_runner.py
  tests/kphp_ci_pipeline_runner.py
Labels: k2

#1324 [k2] update k2-header
  runtime-light/k2-platform/k2-header.h
Labels: k2

#1318 [k2] implement strtotime
  builtin-functions/kphp-light/stdlib/time-functions.txt
  compiler/make/objs-to-k2-component-target.h
  runtime-light/allocator-wrapper/libc-alloc-wrapper.cpp
  runtime-light/k2-platform/k2-api.h
  runtime-light/runtime-light.cmake
  runtime-light/runtime-light.cpp
  runtime-light/state/image-state.h
  runtime-light/state/instance-state.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/time/time-functions.cpp
  runtime-light/stdlib/time/time-functions.h
  runtime-light/stdlib/time/time-state.cpp
  runtime-light/stdlib/time/time-state.h
  runtime-light/stdlib/time/timelib-constants.h
  runtime-light/stdlib/time/timelib-functions.cpp
  runtime-light/stdlib/time/timelib-functions.h
  runtime-light/stdlib/time/timelib-timezone-cache.h
  tests/phpt/dl/459_strtotime.php
  tests/phpt/pk/025_strtotime_next_week_day.php
Labels: k2

#1328 [k2] fix set_timer by using task<> to start a fork
  runtime-light/stdlib/time/timer-functions.h
Labels: k2

#1329 [k2] custom format for floating points in logs
  runtime-light/utils/logs.h
Labels: k2

#1325 [k2] add k2 resolve symbol
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
Labels: k2
