Repository VKCOM/kphp, pull requests merged in 2025-02, with the labels that each got.

#1230 disable static linking of PostgresSQL-related libs
  .github/workflows/debian.yml
  .github/workflows/ubuntu.yml
  cmake/utils.cmake
  runtime-light/runtime-light.cmake
  third-party/curl-cmake/curl.cmake
  third-party/openssl-cmake/openssl.cmake
Labels: bug, CI/CD

#1234 fix runtime allocator deallocate
  runtime-common/core/allocator/script-allocator.h
Labels: bug

#1233 add platform_allocator
  runtime-common/core/allocator/platform-allocator.h
Labels: runtime, k2

#1238 fix msgpack allocations
  runtime-common/stdlib/msgpack/zone.cpp
  runtime-common/stdlib/msgpack/zone.h
Labels: bug, runtime

#1229 do not initialize StringLibContext's static buffers
  runtime-common/stdlib/string/string-context.h
  runtime-common/stdlib/string/string-functions.cpp
  runtime-light/state/instance-state.h
Labels: optimization, runtime, k2

#1235 [k2] implement visitors
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  compiler/code-gen/declarations.cpp
  compiler/code-gen/files/shape-keys.cpp
  runtime-common/core/allocator/platform-allocator.h
  runtime-common/core/std/containers.h
  runtime-common/stdlib/visitors/common-visitors-methods.h
  runtime-common/stdlib/visitors/dummy-visitor-methods.h
  runtime-common/stdlib/visitors/memory-visitors.h
  runtime-light/state/image-state.h
  runtime-light/stdlib/diagnostics/compile-time-location.h
  runtime-light/stdlib/job-worker/job-worker.h
  runtime-light/stdlib/rpc/rpc-extra-info.h
  runtime-light/stdlib/rpc/rpc-state.h
  runtime-light/stdlib/system/system-functions.h
  runtime-light/stdlib/visitors/array-visitors.h
  runtime-light/stdlib/visitors/shape-visitors.h
  runtime/datetime/date_interval.h
  runtime/datetime/datetime.h
  runtime/datetime/datetime_immutable.h
  runtime/datetime/datetime_zone.h
  runtime/dummy-visitor-methods.h
  runtime/exception.h
  runtime/ffi.h
  runtime/instance-cache.h
  runtime/job-workers/job-interface.h
  runtime/kphp_tracing.h
  runtime/memcache.h
  runtime/memory_usage.h
  runtime/mysql.h
  runtime/pdo/pdo.h
  runtime/pdo/pdo_statement.h
  runtime/rpc.h
  runtime/rpc_extra_info.h
  runtime/spl/array_iterator.h
  runtime/to-array-processor.h
  runtime/zlib.cpp
  runtime/zlib.h
  tests/phpt/dl/1034_to_array_debug_shape.php
  tests/phpt/dl/1036_to_array_debug_shape_nullable.php
  tests/phpt/dl/1037_to_array_debug_shape_define.php
  tests/phpt/memory_usage/10_arrays.php
  tests/phpt/memory_usage/11_shapes.php
  tests/phpt/memory_usage/1_primitive_types.php
  tests/phpt/memory_usage/2_classes.php
  tests/phpt/memory_usage/3_lambdas.php
  tests/phpt/memory_usage/4_interfaces.php
  tests/phpt/memory_usage/5_polymorphic_classes.php
  tests/phpt/null_coalescing/10_shapes.php
  tests/phpt/shapes/013_shape_inside_fork.php
  tests/phpt/shapes/014_concat_arrays_of_shapes.php
  tests/phpt/shapes/015_shape_from_fork.php
  tests/phpt/shapes/019_shape_to_array.php
Labels: runtime, k2

#1225 add few builtins in runtime-light
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/system.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  builtin-functions/kphp-light/vkext.txt
  runtime-light/k2-platform/k2-api.h
  runtime-light/k2-platform/k2-header.h
  runtime-light/stdlib/memory/memory-usage.h
  runtime-light/stdlib/serialization/json-functions.h
  runtime-light/stdlib/server/http-functions.h
  runtime-light/stdlib/stdlib.cmake
  runtime-light/stdlib/system/system-functions.cpp
  runtime-light/stdlib/system/system-functions.h
  tests/phpt/json/31_russian_cp1251.php
Labels: k2

#1243 [k2] implement array_reduce
  builtin-functions/kphp-light/array.txt
  builtin-functions/kphp-light/unsupported/arrays.txt
  compiler/code-gen/vertex-compiler.cpp
  runtime-light/stdlib/array/array-functions.h
  tests/phpt/lambdas/018_typed_array_reduce.php
  tests/phpt/lambdas/037_template_internal_functions_as_callbacks.php
  tests/phpt/nn/002_array_reduce.php
  tests/phpt/phc/parsing/impure.php
Labels: k2

#1242 [k2] do not set matches in regex functions unless it's necessary
  runtime-light/stdlib/string/regex-functions.cpp
  runtime-light/stdlib/string/regex-functions.h
  runtime-light/stdlib/string/regex-state.h
Labels: k2
