Repository VKCOM/kphp, pull requests merged in 2025-01, with the labels that each got.

#1200 [k2] refactor http stuff
  runtime-light/server/http/http-server-state.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/http/init-functions.h
  runtime-light/server/init-functions.h
  runtime-light/state/init-functions.cpp
  runtime-light/stdlib/server/http-functions.cpp
  runtime-light/stdlib/server/http-functions.h
Labels: refactoring, k2

#1205 prevent false-positive stack-buffer-overflow ASan detections on signal stack, attemp 2
  server/php-runner.cpp
  server/signal-handlers.cpp
  server/signal-handlers.h
Labels: bug, small fix, runtime

#1206 adjust timeouts for `004_sched_yield_sleep` test
  tests/phpt/fork/004_sched_yield_sleep.php
Labels: small fix

#1203 [k2] refactor TL library
  runtime-light/allocator/allocator.h
  runtime-light/k2-platform/k2-api.h
  runtime-light/server/http/init-functions.cpp
  runtime-light/server/job-worker/init-functions.h
  runtime-light/state/init-functions.cpp
  runtime-light/state/instance-state.cpp
  runtime-light/state/instance-state.h
  runtime-light/stdlib/component/component-api.cpp
  runtime-light/stdlib/confdata/confdata-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/file/resource.cpp
  runtime-light/stdlib/job-worker/job-worker-api.cpp
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/tl/tl-core.cpp
  runtime-light/tl/tl-core.h
  runtime-light/tl/tl-functions.cpp
  runtime-light/tl/tl-functions.h
  runtime-light/tl/tl-types.cpp
  runtime-light/tl/tl-types.h
  runtime-light/tl/tl.cmake
Labels: refactoring, k2

#1210 [k2] implement preg_replace_callback
  builtin-functions/kphp-light/regex.txt
  runtime-light/stdlib/string/regex-functions.cpp
  runtime-light/stdlib/string/regex-functions.h
  tests/phpt/regexp/001_string_result.php
  tests/phpt/regexp/002_null_error.php
Labels: k2

#1211 [k2] add missing RPC bultins
  builtin-functions/kphp-light/rpc.txt
  runtime-light/stdlib/rpc/rpc-api.cpp
  runtime-light/stdlib/rpc/rpc-api.h
  runtime-light/stdlib/rpc/rpc-state.h
  runtime-light/tl/tl-builtins.cpp
Labels: k2

#1209 [k2] move ip functions to common
  builtin-functions/kphp-light/server.txt
  builtin-functions/kphp-light/unsupported/unsupported-server.txt
  runtime-common/stdlib/server/net-functions.cpp
  runtime-common/stdlib/server/net-functions.h
  runtime-common/stdlib/stdlib.cmake
  runtime/interface.cpp
  runtime/interface.h
  tests/phpt/dl/667_geoip.php
Labels: runtime, k2

#1214 [k2][regex] do not pass callback by reference
  runtime-light/stdlib/string/regex-functions.h
Labels: k2

#1217 add extra attempts to store into IC for flakiness avoidance, fix `test_shared_memory_piece_copying`
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/http_worker.php
  tests/python/tests/job_workers/php/SharedMemoryPieceCopying/job_worker.php
Labels: bug, refactoring

#1219 [k2] add std::move when calling shutdown function
  runtime-light/stdlib/server/handler-functions.h
Labels: k2

#1213 Support CompileTimeLocation in K2
  builtin-functions/kphp-light/unsupported/misc.txt
  runtime-light/stdlib/diagnostics/compile-time-location.h
  runtime-light/stdlib/diagnostics/exception-functions.h
  tests/phpt/array/027_explode.php
  tests/phpt/cl/197_compile_time_location.php
Labels: k2

#1221 Pass arguments by value instead of by const ref in coroutines
  runtime-light/stdlib/array/array-functions.h
  runtime-light/stdlib/crypto/crypto-functions.cpp
  runtime-light/stdlib/crypto/crypto-functions.h
  runtime-light/stdlib/exit/exit-functions.cpp
  runtime-light/stdlib/exit/exit-functions.h
  runtime-light/stdlib/file/file-system-functions.cpp
  runtime-light/stdlib/file/file-system-functions.h
  runtime-light/stdlib/time/timer-functions.h
Labels: k2

#1222 [k2] fix runtime compilation from sources
  compiler/make/make.cpp
Labels: k2

#1224 Fix ubuntu 24.04 noble build
  builtin-functions/kphp-full/_functions.txt
  common/dl-utils-lite.cpp
  common/dl-utils-lite.h
  common/stats/provider.cpp
  compiler/pipes/register-kphp-configuration.cpp
  compiler/pipes/register-kphp-configuration.h
  compiler/rewrite-rules/impl/rules_generator.py
  runtime/interface.cpp
  runtime/interface.h
  runtime/runtime.cmake
  runtime/thread-pool.cpp
  runtime/thread-pool.h
  server/php-engine.cpp
  server/php-master.cpp
  server/server-stats.cpp
  server/server-stats.h
  tests/phpt/kphp_configuration/10_thread_pool_size.php
  third-party/BS_thread_pool.hpp
Labels: runtime, compiler

#1204 changed the output of the encodings for `mb_functions` to the correct function
  builtin-functions/kphp-full/kphp_toggles.txt
  builtin-functions/kphp-light/kphp-toggles.txt
  runtime-common/stdlib/string/mbstring-functions.cpp
  runtime-common/stdlib/string/mbstring-functions.h
  runtime-common/stdlib/string/string-context.h
  runtime/interface.cpp
Labels: runtime
